
mqtt:
  binary_sensor:
    - name: "NVR Camera 1 Motion"
      unique_id: nvr_camera_1_motion
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json.index == "0" and value_json.Code == "VideoMotion" %}
        {{ value_json.action }}
        {% else %}
        {{ states("binary_sensor.nvr_camera_1_motion") }}
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"
    - name: "NVR Camera 1 Crossline"
      unique_id: nvr_camera_1_crossline
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json.index == "0" and value_json.Code == "CrossLineDetection" %}
        {{ value_json.action }}
        {% else %}
        {{ states("binary_sensor.nvr_camera_1_crossline") }}
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 1 Sound"
      unique_id: nvr_camera_1_sound
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "0" and value_json.Code == "AudioMutation" %}
              {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_1_sound") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 2 Motion"
      unique_id: nvr_camera_2_motion
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json.index == "1" and value_json.Code == "VideoMotion" %}
        {{ value_json.action }}
        {% else %}
        {{ states("binary_sensor.nvr_camera_2_motion") }}
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"
    - name: "NVR Camera 2 Crossline"
      unique_id: nvr_camera_2_crossline
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json.index == "1" and value_json.Code == "CrossLineDetection" %}
        {{ value_json.action }}
        {% else %}
        {{ states("binary_sensor.nvr_camera_2_crossline") }}
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 2 Sound"
      unique_id: nvr_camera_2_sound
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "1" and value_json.Code == "AudioMutation" %}
              {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_2_sound") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 7 Motion"
      unique_id: nvr_camera_7_motion
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "6" and value_json.Code == "VideoMotion" %}
            {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_7_motion") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 7 Sound"
      unique_id: nvr_camera_7_sound
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "6" and value_json.Code == "AudioMutation" %}
              {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_7_sound") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

automation:
  - id: b6d4aa88-52a2-4e29-afc8-4df17f17e212
    alias: Camera Front Crossline Notification
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.nvr_camera_1_crossline
        from: "off"
        to: "on"
    condition: []
    action:
      - alias: "Notify Michael"
        service: notify.mobile_app_kashyyyk
        data:
          title: Taliluna Security
          message: Front Camera Motion
          data:
            entity_id: camera.192_168_40_208_channel_1
      - delay:
          minutes: 30

  - id: 55ecfc8e-fffb-4b80-9ee6-1092ead747aa
    alias: Camera Rear Crossline Notification
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.nvr_camera_2_crossline
        from: "off"
        to: "on"
    condition: []
    action:
      - alias: "Notify Michael"
        service: notify.mobile_app_kashyyyk
        data:
          title: Taliluna Security
          message: Back Camera Motion
          data:
            entity_id: camera.192_168_40_208_channel_2
      - delay:
          minutes: 30
    
  - id: 6709971c-5025-4903-a1ba-eb033701e7c3
    alias: Camera Grab Snapshots
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.nvr_camera_1_motion
          - binary_sensor.nvr_camera_2_motion
          - binary_sensor.nvr_camera_7_motion
          - binary_sensor.nvr_camera_1_sound
          - binary_sensor.nvr_camera_2_sound
          - binary_sensor.nvr_camera_7_sound
        from: "off"
        to: "on"
    condition: []
    action:
      - variables:
          camera_number: >-
            {{ 'binary_sensor.nvr_camera_1_motion' | regex_findall('camera_(\d)') }}
          camera_id: >-
            {{ 'camera.192_168_40_208_channel_' {{ camera_number }} }}
          snapshot_path: >-
            {{ '/config/www/camera_snapshot_' {{camera_number}} '.jpg'}}
      - alias: "Take a snapshot"
        service: camera.snapshot
        target:
          entity_id: "{{ camera_id }}"
        data:
          filename: "{{ snapshot_path }}"