group:
  locks_all:
    name: "All Locks"
    entities:
      - lock.touchscreen_electronic_deadbolt
      - lock.touchscreen_electronic_deadbolt_2
      - lock.touchscreen_electronic_deadbolt_3

lock:
  - platform: template
    name: All Locks
    value_template: >-
      {{
        is_state('lock.touchscreen_electronic_deadbolt', 'locked') and
        is_state('lock.touchscreen_electronic_deadbolt_2', 'locked') and
        is_state('lock.touchscreen_electronic_deadbolt_3', 'locked')
      }}
    lock:
      service: lock.lock
      target:
        entity_id:
          - lock.touchscreen_electronic_deadbolt
          - lock.touchscreen_electronic_deadbolt_2
          - lock.touchscreen_electronic_deadbolt_3
    unlock:
      service: lock.unlock
      target:
        entity_id:
          - lock.touchscreen_electronic_deadbolt
          - lock.touchscreen_electronic_deadbolt_2
          - lock.touchscreen_electronic_deadbolt_3
  - platform: template
    name: Garage Door
    optimistic: True
    value_template: >-
      {{ is_state('binary_sensor.tilt_shock_xs_sensor_access_control_window_door_is_open', 'off')}}
    lock:
      service: switch.turn_on
      target:
        entity_id: switch.multirelay_2
    unlock:
      service: switch.turn_on
      target:
        entity_id: switch.multirelay_2

input_select:
  node_20_access_label:
    name: Front Door Access Label
    options:
      - RF unlock operation
      - RF lock operation
      - Keypad unlock operation
      - Keypad lock operation
      - Manual unlock operation
      - Manual lock operation
  node_21_access_label:
    name: Back Door Access Label
    options:
      - RF unlock operation
      - RF lock operation
      - Keypad unlock operation
      - Keypad lock operation
      - Manual unlock operation
      - Manual lock operation
  node_22_access_label:
    name: Laundry Door Access Label
    options:
      - RF unlock operation
      - RF lock operation
      - Keypad unlock operation
      - Keypad lock operation
      - Manual unlock operation
      - Manual lock operation

input_number:
  node_20_user_code:
    name: Front Door User Code
    min: 0
    max: 30
  node_21_user_code:
    name: Back Door User Code
    min: 0
    max: 30
  node_22_user_code:
    name: Laundry Door User Code
    min: 0
    max: 30

automation:
  - alias: Lock locks when it's late
    id: 74ffe94e-c2e3-43c3-9eef-395ae0e81a38
    trigger:
      - platform: time_pattern
        minutes: "0"
    condition:
      - alias: "Only when it's late"
        condition: time
        after: "23:00:00"
        before: "05:00:00"
      - alias: "Not in guest mode"
        condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - alias: "All locks not locked"
        condition: state
        entity_id: lock.all_locks
        state: "unlocked"
    action:
      - alias: "Run lock deadbolts scrips"
        service: script.lock_deadbolts_if_doors_shut

  - alias: Lock Status Report
    id: b237632a-cd0b-42b5-9d35-de1104b7e526
    trigger:
      - platform: event
        event_type: zwave_js_notification
        event_data:
          label: Access Control
    action:
      - alias: "notify test"
        service: script.notify_michael
        data:
          title: Taliluna Debug
          message: >-
            {{ trigger.event.data.node_id }}: {{ trigger.event.data.event_label }}
          alert_level: Debug
      - alias: "Set access label"
        service: input_select.select_option
        target:
          entity_id: "input_select.node_{{trigger.event.data.node_id}}_access_label"
        data:
          option: "{{trigger.event.data.event_label}}"
      - alias: "Set user code"
        service: input_number.set_value
        target:
          entity_id: "input_number.node_{{trigger.event.data.node_id}}_user_code"
        data:
          value: >-
            {% if "userId" in trigger.event.data.parameters -%}
            {{ trigger.event.data.paramters.userId}}
            {%- else -%}
            0
            {%- endif %}
        # event_type: zwave_js_notification
        # data:
        #   domain: zwave_js
        #   node_id: 20
        #   home_id: 3996165589
        #   device_id: 78ef68f06b91d579cf2e9c55119ffe5d
        #   command_class: 113
        #   command_class_name: Notification
        #   label: Access Control
        #   type: 6
        #   event: 6
        #   event_label: Keypad unlock operation
        #   parameters:
        #     userId: 1
        # origin: LOCAL
        # time_fired: "2023-02-25T14:52:17.621607+00:00"
        # context:
        #   id: 01GT4GYXTN94SX7ZXZA5ENFHAH
        #   parent_id: null
        #   user_id: null

script:
  lock_deadbolts_if_doors_shut:
    alias: "Lock locks or notify if open"
    sequence:
      - variables:
          open_door_names: >-
            {{ expand('group.door_sensors_simply_safe')
              | selectattr("state", "==", "on")
              | map(attribute='attributes.friendly_name')
              | list }}
      - if:
        - alias: "Check if door with lock is open"
          condition: template
          value_template: "{{ open_door_names | length > 0 }}"
        then:
        - alias: "Notify if door sensor open"
          service: script.notify_parents
          data:
            alert_level: Info
            title: Taliluna Security
            message: >-
              Cannot lock {{ open_door_names | join(", ") }}
      - if:
          - alias: "Front door closed"
            condition: state
            entity_id: binary_sensor.front_door_entry
            state: "off"
        then:
          - alias: "Lock front door"
            service: lock.lock
            target:
              entity_id: lock.touchscreen_electronic_deadbolt
      - if:
          - alias: "Back door closed"
            condition: state
            entity_id: binary_sensor.back_door_entry
            state: "off"
        then:
          - alias: "Lock back door"
            service: lock.lock
            target:
              entity_id: lock.touchscreen_electronic_deadbolt_2
      - if:
          - alias: "Laundry door closed"
            condition: state
            entity_id: binary_sensor.laundry_door_entry
            state: "off"
        then:
          - alias: "Lock laundry door"
            service: lock.lock
            target:
              entity_id: lock.touchscreen_electronic_deadbolt_3