binary_sensor:
  - platform: template
    sensors:
      motion_server_cabinet:
        device_class: motion
        friendly_name: "Kitchen Motion"
        value_template: >-
          {{ states("binary_sensor.pir_motion_detector_any") == "on" }}
      motion_hallway:
        device_class: motion
        friendly_name: "Hallway Motion"
        value_template: >-
          {{ states("binary_sensor.pir_motion_detector_any_2") == "on" }}
      motion_camille_bedroom:
        device_class: motion
        friendly_name: "Camille's Bedroom Motion"
        value_template: >-
          {{ states("binary_sensor.4_in_one_multisensor_any") == "on" }}
      motion_living_room:
        device_class: motion
        friendly_name: "Living Room Motion"
        value_template: >-
          {{ states("sensor.linear_wapirz_1_motion_sensor_alarm_level_3")|float > 0 }}
      motion_master_bedroom:
        device_class: motion
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {{ states("binary_sensor.multisensor_6_home_security_motion_detection") == "on" }}

group:
  motion_sensors:
    name: All Motion Sensors
    entities:
      # - binary_sensor.motion_server_cabinet
      - binary_sensor.motion_hallway
      - binary_sensor.motion_camille_bedroom
      # - binary_sensor.motion_living_room
      - binary_sensor.motion_master_bedroom
