binary_sensor:
  - platform: template
    sensors:
        door_sensor_1:
          device_class: opening
          friendly_name: "Master Closet Door"
          value_template: >-
            {{ states("binary_sensor.door_windows_sensor_any_2") == "on" }}
        door_sensor_2:
          device_class: opening
          friendly_name: "Front Door"
          value_template: >-
            {{ states("binary_sensor.lumi_lumi_sensor_magnet_aq2_8a344f04_on_off") == 'on'}}
        door_sensor_3:
          device_class: opening
          friendly_name: "Laundry Closet Door"
          value_template: >-
            {{ states("binary_sensor.door_windows_sensor_any") == "on" }}
        door_sensor_4:
          device_class: opening
          friendly_name: "Front Closet Door"
          value_template: >-
            {{ states("binary_sensor.door_windows_sensor_any_3") == "on" }}
        door_sensor_5:
          device_class: opening
          friendly_name: "Camille's Closet"
          value_template: >-
            {{ states("binary_sensor.door_windows_sensor_any_4") == "on" }}

input_boolean:
  door_alert_delay:
    name: Door Alert Delay
    icon: mdi:bell-off
    initial: off

group:
  door_sensors:
    name: "All Door Sensors"
    entities:
      - binary_sensor.door_sensor_1
      - binary_sensor.door_sensor_2
      - binary_sensor.door_sensor_3
      - binary_sensor.door_sensor_4
      - binary_sensor.door_sensor_5
  door_sensors_simply_safe:
    name: "Simply Safe Door Sensors"
    entities:
      - binary_sensor.front_door_entry
      - binary_sensor.back_door_entry
      - binary_sensor.laundry_door_entry