group:
  moisture_sensors:
    name: Moisture Sensor
    entities:
      - binary_sensor.laundry_water_leak_sensor_water_leak_detected
      - binary_sensor.smartthings_moisture_ias_zone
automation:
  - alias: Water Leak Alert
    id: 6de6cef3-2d81-4ce1-a555-4e800c9c3867
    trigger:
      - platform: state
        entity_id: group.moisture_sensors
        from: "off"
        to: "on"
      - platform: time_pattern
        minutes: "/15"
    condition:
      - alias: "Water leak detected"
        condition: state
        entity_id: group.moisture_sensors
        state: "on"
    action: 
      - variables:
          entities: >-
            {% for sensor in expand("group.moisture_sensors") if sensor.state == "on" -%}
              {{ state_attr(sensor.entity_id, "friendly_name") }}
              {%- if not loop.last %}, {% endif -%}
            {%- endfor %}
      - alias: "Send low battery notification"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Water detected on {{ entities }}
          alert_level: Warn
