camera:
  - platform: local_file
    camera_path: /config/www/snapshot.jpg
    name: Local Test

mqtt:
  binary_sensor:
    - name: "NVR Camera 8 Motion"
      unique_id: nvr_camera_8_motion
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json.index == "7" and value_json.Code == "VideoMotion" %}
        {{ value_json.action }}
        {% else %}
        {{ states("binary_sensor.nvr_camera_8_motion") }}
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"
    - name: "NVR Camera 8 Crossline"
      unique_id: nvr_camera_8_crossline
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json.index == "7" and value_json.Code == "CrossLineDetection" %}
        {{ value_json.action }}
        {% else %}
        {{ states("binary_sensor.nvr_camera_8_crossline") }}
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 8 Sound"
      unique_id: nvr_camera_8_sound
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "7" and value_json.Code == "AudioMutation" %}
              {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_8_sound") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 7 Motion"
      unique_id: nvr_camera_7_motion
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "6" and value_json.Code == "VideoMotion" %}
            {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_7_motion") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

    - name: "NVR Camera 7 Sound"
      unique_id: nvr_camera_7_sound
      state_topic: "amcrest2mqtt/AMR03225C8B908F530/event"
      value_template: >-
        {% if value_json is defined %}
          {% if value_json.index == "6" and value_json.Code == "AudioMutation" %}
              {{ value_json.action }}
          {% else %}
          {{ states("binary_sensor.nvr_camera_7_sound") }}
          {% endif %}
        {% else %}
          Stop
        {% endif %}
      payload_on: "Start"
      payload_off: "Stop"
      availability:
        - topic: "amcrest2mqtt/AMR03225C8B908F530/status"
          payload_available: "online"
          payload_not_available: "offline"

automation:
  - id: b6d4aa88-52a2-4e29-afc8-4df17f17e212
    alias: Front Door Crossline Notification
    trigger:
      - platform: state
        entity_id: binary_sensor.nvr_camera_8_crossline
        from: "off"
        to: "on"
    condition: []
    action:
      - alias: "Notify Michael"
        service: notify.mobile_app_kashyyyk
        data:
          title: Taliluna Security
          message: Front Camera Motion
          data:
            entity_id: camera.192_168_40_208_channel_8_snapshot