automation:
  - id: c24f8ba3-24f3-4299-b2ae-d49f57c8cd50
    alias: Notify about smoke/co
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_detected
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_carbon_monoxide_detected
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_replacement_required_end_of_life
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_alarm_test
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_alarm_silenced
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_detected_2
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_carbon_monoxide_detected_2
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_replacement_required_end_of_life_2
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_alarm_test_2
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_alarm_silenced_2
          - binary_sensor.zcombo_g_smoke_co_alarm_smoke_alarm_smoke_detected_3
          - binary_sensor.zcombo_g_smoke_co_alarm_co_alarm_carbon_monoxide_detected_3
        from: "off"
        to: "on"
    action:
      - alias: "Notify parents"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: "{{ state_attr(trigger.entity_id, 'friendly_name') }}"
          alert_level: Warn