automation:
  # Opening front door or patio door will trigger alarm
  - alias: Alarm Control Panel Trigger All
    trigger:
      - platform: state
        entity_id:
          - input_boolean.alarm_control_panel_trigger
          - binary_sensor.door_sensor_2
          # - binary_sensor.door_sensor_3
          # Now that we have a door we don't want to trigger alarms with patio
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
      - condition: state
        entity_id: input_boolean.in_home_services
        state: "off"
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Control Panel Trigger All Service Present
    trigger:
      - platform: state
        entity_id:
          - input_boolean.alarm_control_panel_trigger
          - binary_sensor.door_sensor_2
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
      - condition: state
        entity_id: input_boolean.in_home_services
        state: "on"
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm

  # Motion in the house will trigger alarm when set to away
  - alias: Alarm Control Panel Trigger Away
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_1
          - binary_sensor.door_sensor_3
          - binary_sensor.motion_camille_bedroom
          - binary_sensor.motion_hallway
          # - binary_sensor.motion_living_room
          - binary_sensor.motion_office
          - binary_sensor.motion_master_bedroom
        to: 'on'
    condition:
      - condition: template
        value_template: >-
         {{ states("alarm_control_panel.home_alarm") == "armed_away" }}
    action:
      - service: alarm_control_panel.alarm_trigger
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Arm Night Buttons
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_master_bedroom_2
          - input_boolean.flic_button_hold
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Arm Away Buttons
    trigger:
      - platform: state
        entity_id:
         - input_boolean.minimote_front_door_2
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Disarm Buttons
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_master_bedroom_8
          - input_boolean.minimote_front_door_8
          - input_boolean.flic_button_single_click
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: ALARM_DISARM
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") != "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: input_boolean.turn_off
        entity_id: input_boolean.in_home_services
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display

  - alias: Alarm Disarm Morning Routine
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_hallway
          - binary_sensor.motion_living_room
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "armed_night"
      - condition: numeric_state
        entity_id:
          - binary_sensor.motion_master_bedroom
          - binary_sensor.motion_camille_bedroom
        value_template: >-
          {{((now() | as_timestamp) - (state.last_changed | as_timestamp)) / 60 }}
        below: 15
      - condition: time
        after: "05:00:00"
        before: "12:00:00"
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm

  - alias: Alarm Disarm When Triggered
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_master_bedroom_1
          - input_boolean.minimote_master_bedroom_2
          - input_boolean.minimote_master_bedroom_3
          - input_boolean.minimote_master_bedroom_4
          - input_boolean.minimote_master_bedroom_5
          - input_boolean.minimote_master_bedroom_6
          - input_boolean.minimote_master_bedroom_7
          - input_boolean.minimote_master_bedroom_8
          - input_boolean.minimote_front_door_8
          - input_boolean.flic_button_single_click
          - input_boolean.flic_button_hold
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: ALARM_DISARM
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "triggered" }}
    action:
      - service: alarm_control_panel.alarm_disarm
        entity_id: alarm_control_panel.home_alarm
      - service: switch.turn_off
        entity_id: switch.linear_unknown_type_2005_id_0503_switch
      - service: input_boolean.turn_off
        entity_id: input_boolean.in_home_services
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_display

  - alias: Set Away from push message
    trigger:
      - platform: event
        event_type: ios.notification_action_fired
        event_data:
          actionName: ALARM_ARM_AWAY
    condition:
      - condition: template
        value_template: >-
          {{ states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm

  - alias: In Home Service Over
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_2
        from: "on"
        to: "off"
        for:
          minutes: 45
    condition:
      - condition: state
        entity_id: input_boolean.in_home_services
        state: "on"
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "disarmed"
      - condition: state
        entity_id: group.motion_sensors
        state: "off"
        for:
          minutes: 40
      - condition: template
        value_template: >-
          {{ states("input_select.michael_status") != "Home" and
             states("input_select.angela_status") != "Home" }}
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.in_home_services
      - service: alarm_control_panel.alarm_arm_away
        entity_id: alarm_control_panel.home_alarm
      - service: notify.notify
        data:
          title: Alarm
          message: "There has been no motion for 45 minutes. The alarm is set to Armed Away"
