input_datetime:
  house_wakeup_time:
    name: House Wake-up Time
    has_date: false
    has_time: true
  house_sleep_time:
    name: House Sleep Time
    has_date: false
    has_time: true

automation:
  - alias: Alarm sync to home status
    id: 3c0ba6b0-9a4c-4367-890c-79b3a173a104
    mode: queued
    max_exceeded: silent
    trigger:
      - platform: state
        entity_id: 
          - input_select.home_status
          - alarm_control_panel.simplisafe
    condition:
      condition:
        - alias: "Verify that this automation didn't trigger"
          condition: template
          value_template: >-
            {{ trigger.to_state.context.parent_id == None or 
               (trigger.to_state.context.id != this.context.id and 
               trigger.to_state.context.parent_id != this.context.id) }}
    action:
      - alias: "Pick action based on trigger"
        choose:
        - conditions: >-
            {{ trigger.entity_id == "input_select.home_status" }}
          sequence:
            - alias: "Set alarm based on home status"
              choose:
              - conditions: >-
                  {{ trigger.to_state.state == "Away"}}
                sequence:
                  - alias: "Set alarm away"
                    service: alarm_control_panel.alarm_arm_away
                    target:
                      entity_id: alarm_control_panel.simplisafe
              - conditions: >-
                  {{ trigger.to_state.state in ["Secure", "Sleep"]}}
                sequence:
                  - alias: "Set alarm home"
                    service: alarm_control_panel.alarm_arm_home
                    target:
                      entity_id: alarm_control_panel.simplisafe
              - conditions: >-
                  {{ trigger.to_state.state in ["Normal", "Service", "Guest"]}}
                sequence:
                  - alias: "Set alarm home"
                    service: alarm_control_panel.alarm_disarm
                    target:
                      entity_id: alarm_control_panel.simplisafe
        default:
            - alias: "Set home status based on alarm"
              choose:
              - conditions:
                  - "{{ trigger.to_state.state == 'disarmed' }}"
                  - "{{ states('input_select.home_status') not in ['Guest', 'Alert'] }}"
                sequence:
                  - alias: "set home status in disarmed state"
                    service: input_select.select_option
                    target:
                      entity_id: input_select.home_status
                    data:
                      option: >-
                        {%- if is_state("input_select.home_status", "Service Expected") -%}
                          Service
                        {%- elif is_state("input_select.home_status", "Guest Expected") -%}
                          Guest
                        {%- else -%}
                          Normal
                        {%- endif -%}
              - conditions:
                  - "{{ trigger.to_state.state == 'armed_away' }}"
                  - "{{ states('input_select.home_status') not in ['Guest Expected', 'Service Expected', 'Alert'] }}"
                sequence:
                  - alias: "set home status in armed_away state"
                    service: input_select.select_option
                    target:
                      entity_id: input_select.home_status
                    data:
                      option: >-
                        {%- if is_state("input_select.home_status", "Guest") -%}
                          Guest Expected
                        {%- else -%}
                          Away
                        {%- endif -%}
              - conditions:
                  - "{{ trigger.to_state.state == 'armed_home' }}"
                  - "{{ states('input_select.home_status') not in ['Alert', 'Guest', 'Sleep'] }}"
                sequence:
                  - alias: "set home status in armed_home state"
                    service: input_select.select_option
                    target:
                      entity_id: input_select.home_status
                    data:
                      option: >-
                        {%- if is_state("input_select.home_status", "Guest Expected") -%}
                          Guest
                        {%- else -%}
                          Secure
                        {%- endif -%}
              - conditions:
                  - "{{ trigger.to_state.state == 'triggered' }}"
                sequence:
                  - alias: "set home status in triggered state"
                    service: input_select.select_option
                    target:
                      entity_id: input_select.home_status
                    data:
                      option: Alert

  - alias: "Alarm disarm home in morning"
    id: c07fa84f-0615-40d0-8f54-f2871f1993c0 
    trigger:
      - platform: time
        at: input_datetime.house_wakeup_time
    condition:
      - alias: "Home status is sleep"
        condition: state
        entity_id: input_select.home_status
        state: "sleep"
    action:
      - alias: "Set home status to normal"
        service: input_select.set_options
        target:
          entity_id: input_select.home_status
        data:
          option: Normal

  - alias: Alarm set mode to sleep
    id: 277d896a-aa62-4d17-a62b-f78e179e1592
    trigger:
      - platform: time
        at: 
          - "00:30:00"
          - "01:30:00"
          - "02:30:00"
    condition:
      - alias: "Someone is home"
        condition: state
        entity_id: binary_sensor.location_someone_home
        state: "on"
      - alias: "Home status is normal or secure"
        condition: template
        value_template: >-
           {{ states('input_select.home_status') in 
              ['Normal', 'Secure']}}
    action:
      - alias: "Call alarm set after notify script"
        service: script.alarm_set_after_notify
        data:
          status_option: Normal

  - alias: Alarm set mode to away
    id: 51884c97-27ca-4634-885f-27478a6b30b6
    trigger:
      - platform: state
        entity_id: binary_sensor.location_someone_home
        from: "on"
        to: "off"
        for: "00:15:00"
    condition:
      - alias: "Home status not secure"
        condition: template
        value_template: >-
          {{ states('input_select.home_status') in 
             ['Normal', 'Secure']}}
    action:
      - alias: "Call alarm set after notify script"
        service: script.alarm_set_after_notify
        data:
          status_option: Away

script:
  alarm_set_after_notify:
    alias: "Alarm Set After Notify"
    fields:
      status_option:
        description: Option to set home status
        example: Away
    sequence:
      - alias: "Notify Michael"
        service: notify.mobile_app_kashyyyk
        data:
          title: "Taliluna Alert"
          message: "Home set to {{ status_option }} in 5 minutes"
          data:
            actions:
              - action: "DO_NOT_ARM_ALARM"
                title: "Do not arm"
      - alias: "Wait for response"
        wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "DO_NOT_ARM_ALARM"
        timeout:
          minutes: 5
      - if:
          - "{{ wait.completed }}"
        then:
          - alias: "Secure home"
            service: input_select.select_option
            target:
              entity_id: input_select.home_status
            data:
              option: "{{ status_option }}"
