binary_sensor:
  - platform: template
    sensors:
      motion_hallway:
        device_class: motion
        friendly_name: "Laundry Motion"
        value_template: >-
          {{ states("binary_sensor.pir_motion_detector_any_2") == "on" }}
      motion_camille_bedroom:
        device_class: motion
        friendly_name: "Camille's Bedroom Motion"
        value_template: >-
          {{ states("binary_sensor.4_in_one_multisensor_any") == "on" }}
      motion_master_bedroom:
        device_class: motion
        friendly_name: "Master Bedroom Motion"
        value_template: >-
          {{ states("binary_sensor.multisensor_6_home_security_motion_detection") == "on" }}

group:
  motion_sensors:
    name: All Motion Sensors
    entities:
      - binary_sensor.pir_motion_detector_any
      - binary_sensor.motion_laundry
      - binary_sensor.motion_camille_bedroom
      - binary_sensor.motion_master_bedroom
