group:
  lights_whole_house:
    name: All lights in the house
    entities:
      # Living Room Lamp Left
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Metal Lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Angela's bedroom lamp
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Nani's Lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      # - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off

  lights_away:
    name: All lights when away
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # office closet
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Metal lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Bedside lamps
      - light.smart_switch_6_2
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Garage
      - light.master_bath_1_level_light_color_on_off
      - light.master_bath_4_level_light_color_on_off
  
  lights_alarm_home:
    name: All lights when alarm set to home
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # office closet
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off

  lights_alarm_disabled:
    name: All lights when alarm is disable
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off

  switches_whole_house:
    name: All switches in the house
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Living Room Lamp Left
      - switch.smart_switch_6
      # Michael's Lamp
      - switch.smart_switch_6_2
      # Camille's power strip
      - switch.z_wave_plus_power_strip_ver_2_0
      # - switch.z_wave_plus_power_strip_ver_2_0_2
      # - switch.z_wave_plus_power_strip_ver_2_0_3
      # - switch.z_wave_plus_power_strip_ver_2_0_4
      - switch.z_wave_plus_power_strip_ver_2_0_5
  
  switches_away:
    name: All switches when away
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # HiFi Plug
      - switch.smart_switch_6
      # Wooly
      - switch.z_wave_plus_power_strip_ver_2_0_5
  
  switches_alarm_disabled:
    name: All switches when alarm disabled
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Wooly
      - switch.z_wave_plus_power_strip_ver_2_0_5

  media_whole_house:
    name: All media in the house
    entities:
      - media_player.master_bedroom_speaker
      - media_player.camille_s_room_speaker_2
      - media_player.airplay_hi_fi
      - media_player.samsung_the_frame_65
      - media_player.kitchen_display
      - media_player.office_speaker

automation:
  - alias: "Alarm set to home actions"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_home"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_alarm_home
            - group.switches_away
      - alias: "Lock deadbolts"
        service: script.lock_deadbolts_if_doors_shut

  - alias: "Alarm set to away actions"
    id: b00ba9d7-e3f4-429d-944d-738084944767
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - alias: Turn things off
        service: homeassistant.turn_off
        target:
          entity_id:
            - group.lights_away
            - group.switches_away
      - alias: "Lock deadbolts"
        service: script.lock_deadbolts_if_doors_shut
      # - alias: "Pause all media"
      #   service: media_player.media_pause
      #   target:
      #     entity_id: group.media_whole_house
  
  - alias: Alarm disarmed from away
    id: 04e624e3-69cf-4a7d-87ac-f6e53ad4db15
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_away"
        to: "disarmed"
    condition: []
    action:
      - alias: "Unlock front deadbolt"
        service: lock.unlock
        target:
          entity_id: lock.touchscreen_electronic_deadbolt
      - alias: "Turn things on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - group.lights_alarm_disabled
            - group.switches_alarm_disabled
  
  - id: a2bb76db-1387-4be0-b939-eb84ecbb7ea1
    alias: Alarm disarmed from home
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_home"
        to: "disarmed"
    condition: []
    action:
      - alias: "Turn things on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - group.lights_alarm_disabled
            - group.switches_alarm_disabled

script:
  turn_everything_off:
    alias: "Turn everything off"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_media:
    alias: "Turn off all media"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_home:
    alias: "Turn everything off alarm set to home"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_alarm_home
            - group.switches_alarm_home
      - service: script.lock_deadbolts_if_doors_shut

  turn_off_away:
    alias: "Turn everything off away"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_away
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house
      - service: script.lock_deadbolts_if_doors_shut
  
  return_from_away:
    alias: "Return from away"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_away
            - group.switches_whole_house