group:
  christmas_lights:
    name: Christmas Lights
    entities:
      - light.wled_master
      - switch.smart_switch_6_2

automation:
  - alias: Christmas lights on at dusk
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: homeassistant.turn_on
        entity_id: group.christmas_lights

  - alias: Christmas lights off at 1am
    trigger:
      - platform: time
        at: "01:00:00"
    action:
      - service: homeassistant.turn_off
        entity_id: group.christmas_lights
