input_boolean:
  camille_med_notification_enabled:
    name: Camille Medication Notification On

input_select:
  camille_status:
    name: "Camille's Status"
    options:
      - Home
      - School
      - Away
      - Asleep

input_datetime:
  camille_meds_morning:
    name: "Camille's Morning Med Time"
    has_date: false
    has_time: true
  camille_meds_evening:
    name: "Camille's Evening Med Time"
    has_date: false
    has_time: true

group:
  lights_bedroom_camille:
    name: Lights in Camille's Room
    entities:
      # Grandma's Lamp
      - light.philips_lwb006_097e3010_level_on_off
      # Canopy lights
      - switch.z_wave_plus_power_strip_ver_2_0_5
      - switch.z_wave_plus_power_strip_ver_2_0
      # Camille's Closet
      # - light.ge_appliances_zll_light_1b550600_level_on_off

automation:

  - alias: "Lights on Motion Camille's Room"
    id: 5f0e3383-0a41-4193-93a6-5fe7cf4403c9
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Asleep" and
             states("input_select.camille_status") != "Away" and
             states("group.lights_bedroom_camille") == "off" and
             states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: group.lights_bedroom_camille
      - service: homeassistant.turn_off
        data:
          entity_id: automation.lights_on_motion_camille_s_room
      - alias: "Turn on closet light only if door open"
        choose:
        - conditions:
            - alias: "Closet door open"
              condition: state
              entity_id: binary_sensor.door_sensor_5
              state: "off"
          sequence:
            service: homeassistant.turn_on
            data:
              entity_id: light.ge_appliances_zll_light_1b550600_level_on_off

  - alias: "Minimote Camille Push 1"
    id: 17963bb0-262e-439d-873a-a6b148fd8f84
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_1
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - switch.z_wave_plus_power_strip_ver_2_0_5

  - alias: "Minimote Camille Hold"
    id: 5203c99e-ae5c-411e-a031-58b29f231d2d
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_camille_2
          - input_boolean.minimote_camille_4
          - input_boolean.minimote_camille_6
          - input_boolean.minimote_camille_8
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >-
            {% if is_state("input_select.camille_status", "Asleep") %}
              {% set runScript = "script.goodmorning_camille" %}
            {% elif is_state("input_select.camille_status", "Home") %}
              {% set runScript = "script.goodnight_camille" %}
            {% else %}
              {% set runScript = "automation.lights_camille_on" %}
            {% endif %}
            {{ runScript }}

  - alias: "Minimote Camille Push 2"
    id: d03bc5e4-ce23-43e7-9da2-5d5196165e1d
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_3
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - light.philips_lwb006_097e3010_level_on_off

  - alias: "Minimote Camille Push 3"
    id: 963391e8-09e0-477d-80bd-717c2c0cd7fc
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_5
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - light.ge_appliances_zll_light_1b550600_level_on_off
  
  - alias: Camille Medication Notifications On
    id: a7e85b57-53c2-4aee-94d6-6fa856a4089e
    trigger:
      - platform: time
        at: input_datetime.camille_meds_morning 
      - platform: time
        at: input_datetime.camille_meds_evening 
    condition: []
    action:
      - alias: "Turn on med notifications"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camille_med_notification_enabled

  - alias: Camille Sent Medication Actionalbe Notification
    id: fb06daa2-4eef-4aa6-817d-be5e7452131c
    mode: restart
    trigger:
      - platform: state
        entity_id: input_boolean.camille_med_notification_enabled
        from: "off"
        to: "on"
      - platform: time_pattern
        minutes: "/15"
    condition:
      - alias: "Med notification enabled"
        condition: state
        entity_id: input_boolean.camille_med_notification_enabled
        state: "on"
    action:
      - alias: "Actionable notification to family"
        service: notify.mobile_app_kashyyyk
        data:
          message: "Time for meds"
          data: 
            actions:
              - action: "CAMILLE_MED_TAKEN"
                title: "Taken"
      - alias: "Wait for response"
        wait_for_trigger:
          platform: event
          event_type: mobile_app_notification_action
          event_data:
            action: "CAMILLE_MED_TAKEN"
      - alias: "Turn off med notifiations"
        choose:
        - conditions: '{{ wait.trigger.event.data.action == "CAMILLE_MED_TAKEN"}}'
          sequence:
            - alias: "Turn off med notification input"
              service: input_boolean.turn_off
              target:
                entity_id: input_boolean.camille_med_notification_enabled

script:
  goodmorning_camille:
    alias: Goodmorning Camille
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - group.lights_bedroom_camille
      - service: homeassistant.turn_off
        data:
          entity_id: automation.wakeup_alarm_repeat_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.7

  goodnight_camille:
    alias: Good Night Camille
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_bedroom_camille
            - light.ge_appliances_zll_light_1b550600_level_on_off
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Asleep"
      - service: homeassistant.turn_on
        data:
          entity_id: automation.wakeup_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.5
      # - entity_id:
      #     - input_boolean.alarm_set_camille
      #     - input_boolean.school_day
      #   service_template: >-
      #     {% if states("sensor.weekday") == "Friday" or
      #        states("sensor.weekday") == "Saturday" %}
      #     homeassistant.turn_off
      #     {% else %}
      #     homeassistant.turn_on
      #     {% endif %}
      - service: script.daisy_goodnight
      - service: notify.notify
        data_template:
          title: "Camille"
          message: >-
            Bedtime!
            Morning alarm is {{ states("input_boolean.alarm_set_camille") }}
            {%- if is_state("input_boolean.alarm_set_camille", "on") %} for{{ " " }}
            {{- states("input_datetime.alarm_time_camille")[0:5] }}
            {%- endif %}.

  camille_meds_notify:
    alias: Camille notify about meds
    sequence:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Did you take your meds?"

  camille_brush_teeth_notify:
    alias: Camille remind to brush teeth
    sequence:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Camille, did you brush your teeth?"
