automation:

  - alias: Garage lights on motion camera
    id: dbd64077-7afc-4460-9427-e0f53a503c6d
    trigger:
      - platform: state
        entity_id: binary_sensor.nvr_camera_7_motion
        from: "off"
        to: "on"
    condition:
      - alias: "Light has been off for a while"
        condition: state
        entity_id: light.master_bath_1_level_light_color_on_off
        state: "off"
        for:
          seconds: 30
    action:
      - alias: "Turn on garage lights"
        service: light.turn_on
        target:
          entity_id:
            - light.master_bath_1_level_light_color_on_off
            - light.master_bath_4_level_light_color_on_off

  - alias: Garage lights on motion general
    id: 2d5cea66-1940-4de9-8c3e-cda17b98fae2
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.pir_motion_detector_any
          - binary_sensor.laundry_door_entry
        from: "off"
        to: "on"
      - platform: state
        entity_id: 
          - lock.garage_door
          - lock.touchscreen_electronic_deadbolt_3
        from: "locked"
        to: "unlocked"
    action:
      - alias: "Turn on garage lights"
        service: light.turn_on
        target:
          entity_id:
            - light.master_bath_1_level_light_color_on_off
            - light.master_bath_4_level_light_color_on_off

  - alias: Garage lights motion off
    id: a80a19b7-c91f-43cb-960c-f04a18b6ab75
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.pir_motion_detector_any
        from: "on"
        to: "off"
        for:
          minutes: 5
      - platform: time_pattern
        minutes: "/30"
    condition:
      - alias: "Motion off for 10 minutes"
        condition: state
        entity_id: binary_sensor.nvr_camera_7_motion
        state: "off"
        for:
          minutes: 5
    action:
      - alias: "Turn off garage lights"
        service: light.turn_off
        target:
          entity_id:
            - light.master_bath_1_level_light_color_on_off
            - light.master_bath_4_level_light_color_on_off
