automation:
  - alias: Office all lights on with switch
    trigger:
      - platform: state
        entity_id:
          - switch.aeotec_zw111_nano_dimmer_switch_2
    condition:
      - condition: template
        value_template: >-
          {{ (states.switch.aeotec_zw111_nano_dimmer_switch_2.last_changed | as_timestamp) <
             (states.light.aeotec_zw111_nano_dimmer_level_2.last_changed | as_timestamp)}}
    action:
      - entity_id: switch.aeon_labs_zw096_smart_switch_6_switch
        service: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}

  - id: 2c09bb16-0859-4b83-bbbf-3b4aa98db6d1
    alias: Office closet off when closed
    trigger:
      - platform: state
        entity_id: binary_sensor.door_windows_sensor_any_3
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "disarmed"
    condition: []
    action:
      - alias: "Turn on if sensor is open"
        service: >-
          {{ 'homeassistant.turn_on'
             if states('binary_sensor.door_windows_sensor_any_3') == 'on'
             else 'homeassistant.turn_off' }}
        target:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
