group:
  lights_living_room:
    name: Living Room Lights
    entities:
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
  switches_living_room:
    name: Living Room Switches
    entities:
      - switch.smart_switch_6
  lights_switches_living_room:
    name: Living Room Switches
    entities:
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      - switch.smart_switch_6

automation:
