automation:
  - alias: Wakeup Living Room
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_living_room
          - binary_sensor.motion_hallway
        to: 'on'
    condition:
      - condition: time
        after: '05:00:00'
        before: '23:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: script.goodmorning_living_room

  - alias: Wakeup Living Room Setup
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "disarmed"
    action:
      - service: homeassistant.turn_on
        entity_id: automation.wakeup_living_room

script:
  tv_time:
    alias: TV Time
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.zooz_zen06_switch
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.8
      - service: light.turn_on
        data:
          entity_id:
            - light.living_room_lamp
          brightness: 127
      - service: light.turn_off
        data:
          entity_id:
            - light.accordian_lamp
          brightness: 127

  radio_time:
    alias: Radio Time
    sequence:
      - service: switch.turn_on
        data:
          entity_id: switch.zooz_zen06_switch
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.3

  get_mellowed:
    alias: Get Mellowed
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            - light.living_room_lamp
          brightness: 35
      - service: light.turn_off
        data:
          entity_id:
            - light.accordion_lamp
            - light.aeotec_zw111_nano_dimmer_level
            - light.aeotec_zw111_nano_dimmer_level_3

  goodmorning_living_room:
    alias: Goodmorning Living Room
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.living_room_tv
          volume_level: 0.3
      - service: light.turn_on
        data:
          entity_id:
            - light.aeotec_zw111_nano_dimmer_level
            - light.aeotec_zw111_nano_dimmer_level_3
            - light.accordion_lamp
            - light.living_room_lamp
          brightness: 255
      - service: switch.turn_on
        data:
          entity_id:
            - switch.zooz_zen06_switch
      - service: homeassistant.turn_off
        data:
          entity_id:
            - automation.wakeup_living_room
