input_boolean:
  guest_mode:
    name: Guest Mode
    icon: mdi:ferry

automation:
  - id: 31acd602-6a65-4d19-bdab-29a5f3e19e45
    alias: Guest mode set home status
    trigger:
      - platform: template
        template_value: >-
          {{ states('input_select.home_status') in
             ['Away', 'Vacation', 'Guest', 'Guest Expected'] }}
      - platform: state
        entity_id: input_boolean.guest_mode
    condition:
      condition:
        - alias: "Verify that this automation didn't trigger"
          condition: template
          value_template: >-
            {{ trigger.to_state.context.parent_id == None or 
               (trigger.to_state.context.id != this.context.id and 
               trigger.to_state.context.parent_id != this.context.id) }}
    action:
      - alias: "Vary response on what triggered"
        choose:
        - conditions: >-
            {{ trigger.entity_id == 'input_select.home_status' }}
          sequence:
            - alias: "Set guest mode on home status"
              service: >-
                {% if states("input_select.home_status") in ['Guest', 'Guest Expected'] -%}
                  input_boolean.turn_on
                {%- else -%}
                  input_boolean.turn_off
                {%- endif %}
              target:
                entity_id: input_boolean.guest_mode
        default:
          - alias: "Set home status on guest mode"
            choose:
            - conditions:
                - "{{ states('input_select.home_status') != 'Alert' }}"
                - alias: "Guest mode on"
                  condition: state
                  entity_id: input_boolean.guest_mode
                  state: "on"
              sequence:
                - alias: "Set home status"
                  service: input_select.set_options
                  target:
                    entity_id: input_select.home_status
                  data:
                    option: >-
                      {% if states("input_select.home_status") in ['Normal', 'Guest'] -%}
                        Guest
                      {%- else -%}
                        Guest Expected
                      {%- endif %}
            - conditions:
                - "{{ states('input_select.home_status') in ['Guest', 'Guest Expected'] }}"
                - alias: "Guest mode off"
                  condition: state
                  entity_id: input_boolean.guest_mode
                  state: "off"
              sequence:
                - alias: "Set home status"
                  service: input_select.set_options
                  target:
                    entity_id: input_select.home_status
                  data:
                    option: >-
                      {% if states("input_select.home_status") == "Guest" -%}
                        Normal
                      {%- else -%}
                        Away
                      {%- endif %}

script:
  guest_lights_on:
    alias: Guest Lights On
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: group.guest_lights
          brightness: 255
      - service: homeassistant.turn_on
        data:
          entity_id: switch.zooz_zen06_switch
  guest_lights_off:
    alias: Guest Lights Off
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: group.guest_lights
          brightness: 64
      - service: homeassistant.turn_off
        data:
          entity_id: group.guest_lights
      - service: homeassistant.turn_off
        data:
          entity_id: switch.zooz_zen06_switch
  guest_lights_dim:
    alias: Dim The Guest Lights
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: group.guest_lights
          brightness: 64
