input_boolean:
  garbage_notification_enabled:
    name: Garbage Notification On
    icon: mdi:delete
  recycle_notification_enabled:
    name: Recycle Notification On
    icon: mdi:recycle

automation:
  - alias: Garbage Recycle Alerts On
    id: dc5118df-3efb-45e8-8c9c-e1514a99431c
    trigger:
      - platform: calendar
        entity_id: calendar.taliluna_michael_pfammatter
        event: start
      - platform: calendar
        entity_id: calendar.taliluna_michael_pfammatter
        event: end
    condition: []
    variables:
      service_type: >-
        {{ "homeassistant.turn_on" if trigger.event == 'start' else "homeassistant.turn_off"}}
    action:
      - if: "{{trigger.calendar_event.summary == 'Garbage'}}"
        then:
          - alias: "Turn on garbage notification input boolean"
            service: "{{service_type}}"
            target:
              entity_id: input_boolean.garbage_notification_enabled
      - if: "{{trigger.calendar_event.summary == 'Recycle'}}"
        then:
          - alias: "Turn on recycle notification input boolean"
            service: "{{service_type}}"
            target:
              entity_id: input_boolean.recycle_notification_enabled

  - id: d1fff5bf-c9b4-4c1b-a470-f8f63b032c70
    alias: Garbage Recycle Notification
    trigger:
      - platform: time_pattern
        minutes: "/15"
    condition:
      - condition: or
        conditions:
          - alias: "Garbage Notify Toggled"
            condition: state
            entity_id:
              - input_boolean.garbage_notification_enabled
            state: "on"
          - alias: "Recycle Notify Toggled"
            condition: state
            entity_id:
              - input_boolean.recycle_notification_enabled
            state: "on"
      - condition: or
        conditions:
          - alias: "Home status is normal"
            condition: state
            entity_id: input_select.home_status
            state: "Normal"
          - alias: "Home status is normal"
            condition: state
            entity_id: input_select.home_status
            state: "Secure"
    variables:
      trash_type: >-
        {{'Garbage' if trigger.entity_id == 'input_boolean.garbage_notification_enabled' else 'Recycle'}}
    action:
      - alias: "Send out the notification"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: "Take out the {{trash_type}}"
          alert_level: Info