automation:
  - alias: Laundry Counter Lights on Motion
    id: d2da8e8f-c726-45af-9ead-e38fb27aa479
    trigger:
      - platform: state
        entity_id: binary_sensor.pir_motion_detector_any_2
        from: "off"
        to: "on"
    condition: []
    action:
      - alias: "Turn on laundry counter light"
        service: homeassistant.turn_on
        target:
          entity_id: switch.smart_switch_6_2

  - alias: Laundry Counter Lights Off
    id: de59dfb7-7e8a-4e5c-bac3-a876e4a09758
    trigger:
      - platform: state
        entity_id: binary_sensor.pir_motion_detector_any_2
        from: "on"
        to: "off"
        for: "00:30:00"
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_away"
        to: "to state"
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_home"
        to: "to state"
    condition: []
    action:
      - alias: "Turn on laundry counter light"
        service: homeassistant.turn_off
        target:
          entity_id: switch.smart_switch_6_2