group:
  lights_whole_house:
    name: All lights in the house
    entities:
      # Living Room Lamp Left
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Metal Lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Angela's bedroom lamp
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      # - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
      # Nani's Lamp
      - light.philips_lwb006_097e3010_level_on_off
      # Master Bath lights
      - light.master_bath_lights_zha_group_0x0002
      # front bathroom lights
      - light.bathroom_lights_zha_group_0x0003

  lights_away:
    name: All lights when away
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # office closet
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Metal lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Bedside lamps
      - light.smart_switch_6_2
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Garage
      - light.master_bath_1_level_light_color_on_off
      - light.master_bath_4_level_light_color_on_off
  
  lights_alarm_home:
    name: All lights when alarm set to home
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # office closet
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off

  lights_alarm_disabled:
    name: All lights when alarm is disable
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off

  switches_whole_house:
    name: All switches in the house
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Living Room Lamp Left
      - switch.smart_switch_6
      # Michael's Lamp
      - switch.smart_switch_6_2
      # Camille's power strip
      - switch.z_wave_plus_power_strip_ver_2_0
      # - switch.z_wave_plus_power_strip_ver_2_0_2
      # - switch.z_wave_plus_power_strip_ver_2_0_3
      # - switch.z_wave_plus_power_strip_ver_2_0_4
      - switch.z_wave_plus_power_strip_ver_2_0_5
  
  switches_away:
    name: All switches when away
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # HiFi Plug
      - switch.smart_switch_6
      # Wooly
      - switch.z_wave_plus_power_strip_ver_2_0_5
  
  switches_alarm_disabled:
    name: All switches when alarm disabled
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Wooly
      - switch.z_wave_plus_power_strip_ver_2_0_5

  media_whole_house:
    name: All media in the house
    entities:
      - media_player.master_bedroom_speaker
      - media_player.camille_s_room_speaker_2
      # - media_player.living_room_tv
      - media_player.airplay_hi_fi
      - media_player.samsung_the_frame_65
      - media_player.kitchen_display
      - media_player.office_speaker

input_boolean:
  porch_lights_default:
    name: Porch Light Default State
    icon: mdi:lightbulb

automation:
  - alias: "Alarm set to home actions"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_home"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_alarm_home
            - group.switches_away
      - alias: "Lock deadbolts"
        service: script.lock_deadbolts_if_doors_shut

  - alias: "Alarm set to away actions"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - alias: Turn things off
        service: homeassistant.turn_off
        target:
          entity_id:
            - group.lights_away
            - group.switches_away
      - alias: "Lock deadbolts"
        service: script.lock_deadbolts_if_doors_shut
      - alias: "Pause all media"
        service: media_player.media_pause
        target:
          entity_id: group.media_whole_house
  
  - id: 04e624e3-69cf-4a7d-87ac-f6e53ad4db15
    alias: Alarm disarmed from away
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_away"
        to: "disarmed"
    condition: []
    action:
      - alias: "Unlock front deadbolt"
        service: lock.unlock
        target:
          entity_id: lock.touchscreen_electronic_deadbolt
      - alias: "Turn things on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - group.lights_alarm_disabled
            - group.switches_alarm_disabled
  
  - id: a2bb76db-1387-4be0-b939-eb84ecbb7ea1
    alias: Alarm disarmed from home
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        from: "armed_home"
        to: "disarmed"
    condition: []
    action:
      - alias: "Turn things on"
        service: homeassistant.turn_on
        target:
          entity_id:
            - group.lights_alarm_disabled
            - group.switches_alarm_disabled

  - alias: Porch lights evening on
    id: 522b5aed-7204-40a3-9aa0-c04abd04eb12
    trigger:
      - platform: sun
        event: sunset
        offset: "00:00:00"
    condition: []
    action:
      - alias: "Turn porch lights on"
        service: light.turn_on
        target:
          entity_id:
            - light.ikea_tradfri_bulb_e26_fe5b90
            - light.tradfri_bulb_e26_ws_opal_1000lm_light
        data:
          brightness: 128
      - alias: "Turn default state on"
        service: input_boolean.turn_on
        target:
          entity_id:
            - input_boolean.porch_lights_default
          
  - alias: Porch lights evening off
    id: 82cdd372-c606-43ba-8e17-97e354234cdb
    trigger:
      - platform: time
        at: "22:45:00"
    condition: []
    action:
      - delay:
          minutes: '{{ range(0, 30) | random | int}}'
      - alias: "Turn porch lights off"
        service: light.turn_off
        target:
          entity_id:
            - light.ikea_tradfri_bulb_e26_fe5b90
            - light.tradfri_bulb_e26_ws_opal_1000lm_light
      - alias: "Turn default state off"
        service: input_boolean.turn_off
        target:
          entity_id:
            - input_boolean.porch_lights_default

  - alias: Porch lights on motion
    id: 901e682a-cdf7-4f31-8026-4b03b9c2b8be
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.nvr_camera_1_crossline
        from: "off"
        to: "on"
      - platform: state
        entity_id: lock.touchscreen_electronic_deadbolt
        from: "locked"
        to: "unlocked"
      - platform: state
        entity_id: lock.garage_door
        from: "locked"
        to: "unlocked"
    condition:
      - alias: "Sun is down"
        condition: state
        entity_id: sun.sun
        state: "below_horizon"
    action:
      - alias: "Turn porch lights on"
        service: light.turn_on
        target:
          entity_id:
            - light.ikea_tradfri_bulb_e26_fe5b90
            - light.tradfri_bulb_e26_ws_opal_1000lm_light
        data:
          brightness: 255
      - wait_for_trigger:
        - platform: state
          entity_id: binary_sensor.nvr_camera_1_crossline
          from: "on"
          to: "off"
          for: 
            minutes: 8
      - alias: "Turn off or dim"
        choose:
        - conditions:
            - alias: "Porch light defaults to on"
              condition: state
              entity_id: input_boolean.porch_lights_default
              state: "on"
          sequence:
            - alias: "Dim porch light"
              service: light.turn_on
              target:
                entity_id:
                  - light.ikea_tradfri_bulb_e26_fe5b90
                  - light.tradfri_bulb_e26_ws_opal_1000lm_light
              data:
                brightness: 128
        default:
            - alias: "Turn off porch lights"
              service: light.turn_off
              target:
                entity_id:
                  - light.ikea_tradfri_bulb_e26_fe5b90
                  - light.tradfri_bulb_e26_ws_opal_1000lm_light

  - alias: Garage lights on motion camera
    id: dbd64077-7afc-4460-9427-e0f53a503c6d
    trigger:
      - platform: state
        entity_id: binary_sensor.nvr_camera_7_motion
        from: "off"
        to: "on"
    condition:
      - alias: "Light has been off for a while"
        condition: state
        entity_id: light.master_bath_1_level_light_color_on_off
        state: "off"
        for:
          seconds: 30
    action:
      - alias: "Turn on garage lights"
        service: light.turn_on
        target:
          entity_id:
            - light.master_bath_1_level_light_color_on_off
            - light.master_bath_4_level_light_color_on_off

  - alias: Garage lights on motion general
    id: 2d5cea66-1940-4de9-8c3e-cda17b98fae2
    trigger:
      - platform: state
        entity_id: 
          - binary_sensor.pir_motion_detector_any
          - binary_sensor.laundry_door_entry
        from: "off"
        to: "on"
      - platform: state
        entity_id: 
          - lock.garage_door
          - lock.touchscreen_electronic_deadbolt_3
        from: "locked"
        to: "unlocked"
    action:
      - alias: "Turn on garage lights"
        service: light.turn_on
        target:
          entity_id:
            - light.master_bath_1_level_light_color_on_off
            - light.master_bath_4_level_light_color_on_off

  - alias: Garage lights motion off
    id: a80a19b7-c91f-43cb-960c-f04a18b6ab75
    mode: single
    trigger:
      - platform: state
        entity_id: binary_sensor.pir_motion_detector_any
        from: "on"
        to: "off"
        for:
          minutes: 5
      - platform: time_pattern
        minutes: "/30"
    condition:
      - alias: "Motion off for 10 minutes"
        condition: state
        entity_id: binary_sensor.nvr_camera_7_motion
        state: "off"
        for:
          minutes: 5
    action:
      - alias: "Turn off garage lights"
        service: light.turn_off
        target:
          entity_id:
            - light.master_bath_1_level_light_color_on_off
            - light.master_bath_4_level_light_color_on_off

script:
  turn_everything_off:
    alias: "Turn everything off"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_media:
    alias: "Turn off all media"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_home:
    alias: "Turn everything off alarm set to home"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_alarm_home
            - group.switches_alarm_home
      - service: script.lock_deadbolts_if_doors_shut

  turn_off_away:
    alias: "Turn everything off away"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_away
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house
      - service: script.lock_deadbolts_if_doors_shut
  
  return_from_away:
    alias: "Return from away"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_away
            - group.switches_whole_house