group:
  lights_living_room:
    name: Living Room Lights
    entities:
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
  switches_living_room:
    name: Living Room Switches
    entities:
      - switch.smart_switch_6
  lights_switches_living_room:
    name: Living Room Switches
    entities:
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      - switch.smart_switch_6

automation:
  - alias: Wakeup Living Room
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_living_room
          - binary_sensor.motion_hallway
        to: 'on'
    condition:
      - condition: time
        after: '05:00:00'
        before: '23:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: script.goodmorning_living_room

  - alias: Wakeup Living Room Setup
    trigger:
      - platform: state
        entity_id: alarm_control_panel.simplisafe
        to: "disarmed"
    action:
      - service: homeassistant.turn_on
        entity_id: automation.wakeup_living_room
