group:
  lights_whole_house:
    name: All lights in the house
    entities:
      # Living Room Lamp Left
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Metal Lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Angela's bedroom lamp
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      # Master closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
      # Laundry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      # - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
      # Nani's Lamp
      - light.philips_lwb006_097e3010_level_on_off
      # Master Bath lights
      - light.master_bath_lights_zha_group_0x0002
      # front bathroom lights
      - light.bathroom_lights_zha_group_0x0003

  lights_away:
    name: All lights when away
    entities:
      # Living Room Lamp Left
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Metal Lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Angela's bedroom lamp
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      # Master closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
      # Laundry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      # - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
      # Nani's Lamp
      - light.philips_lwb006_097e3010_level_on_off
      # Master Bath lights
      - light.master_bath_lights_zha_group_0x0002
      # Front Bathroom Lights
      - light.bathroom_lights_zha_group_0x0003

  lights_switches_for_flashing:
    name: All lights that are good for flashing
    entities:
      # Living Room Lamp Left
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Metal Lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Angela's bedroom lamp
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      # Master closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
      # Laundry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Bedroom lamp left
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      # - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off
      # Nani's Lamp
      - light.philips_lwb006_097e3010_level_on_off

  switches_whole_house:
    name: All switches in the house
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Living Room Lamp Left
      - switch.smart_switch_6
      # Michael's Lamp
      - switch.smart_switch_6_2
      # Camille's power strip
      - switch.z_wave_plus_power_strip_ver_2_0
      # - switch.z_wave_plus_power_strip_ver_2_0_2
      # - switch.z_wave_plus_power_strip_ver_2_0_3
      # - switch.z_wave_plus_power_strip_ver_2_0_4
      - switch.z_wave_plus_power_strip_ver_2_0_5


  media_whole_house:
    name: All media in the house
    entities:
      - media_player.bedroom_speaker
      - media_player.camille_s_speaker
      - media_player.living_room_display
      - media_player.living_room_tv
      - media_player.office_speaker

automation:
  - alias: "Alarm night turn off everything"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_night"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - media_player.bedroom_speaker
            - media_player.living_room_tv
            - media_player.living_room_display

  - alias: "Alarm away turn off everything"
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    action:
      - service: script.turn_everything_off_away

  - alias: "No motion late at night"
    trigger:
      - platform: state
        entity_id: group.motion_sensors
        to: "off"
        for:
          minutes: 45
      - platform: time
        at: "01:05:00"
    condition:
      - condition: time
        after: "01:00:00"
        before: "05:00:00"
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "disarmed"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: template
        value_template: >-
          {{ as_timestamp(states.sensor.time.last_changed) - as_timestamp(states.group.motion_sensors.last_changed) > (44*60)
             and states("group.motion_sensors") == "off" }}
    action:
      - service: alarm_control_panel.alarm_arm_night
        entity_id: alarm_control_panel.home_alarm

  - alias: "Master Closet Door Open Turn On Light"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_4
    action:
      - entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
        service: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}

  - alias: "Whole House Pandemic Light Party at 8pm"
    trigger:
      - platform: time
        at: '20:30:00'
    action:
      - service: script.whole_house_lights_pandemic_flash

  - alias: "Hall bath light on motion"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_hallway
        to: "on"
      - platform: state
        entity_id:
          - binary_sensor.motion_hallway
        to: "off"
        for: "00:10:00"
    condition:
      - alias: "Light already on"
        condition: state
        entity_id:
          - light.bathroom_light_1_level_light_color_on_off
        state: "off"
      - alias: "condition alias (name)"
        condition: time
        after: "22:00:00"
        before: "07:00:00"
    action:
      - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.bathroom_light_4_level_light_color_on_off
              data:
                brightness_pct: 1
        default:
          - service: light.turn_off
            target:
              entity_id:
                - light.bathroom_light_4_level_light_color_on_off

script:
  turn_everything_off:
    alias: "Turn everything off"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_whole_house
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_off_media:
    alias: "Turn off all media"
    sequence:
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house

  turn_everything_off_away:
    alias: "Turn everything off away"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_away
            - group.switches_whole_house
      - service: media_player.media_pause
        data:
          entity_id:
            - group.media_whole_house
  get_dark:
    alias: "Get dark"
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.ge_appliances_zll_light_1b550600_level_on_off
            - light.living_room_lamp
            - switch.aeon_labs_zw096_smart_switch_6_switch
            - switch.aeon_labs_zw096_smart_switch_6_switch_2

  whole_house_lights_pandemic_flash:
    alias: "Flash all lights for the pandemic party"
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:00:02"
      - service: homeassistant.toggle
        data:
          entity_id: group.lights_switches_for_flashing
      - delay: "00:10:00"
      - service: homeassistant.turn_off                
        data:
           entity_id: switch.jasco_products_14284_outdoor_smart_switch_switch
