group:
  lights_master_bedroom:
    name: "Lights Master Bedroom"
    entities:
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      - light.ge_appliances_zll_light_49251600_level_on_off
      - switch.zw096_smart_switch_6_switch_2

  lights_master_bedroom_and_closets:
    name: "Lights in Master Bedroom and Closets"
    entities:
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      - light.ge_appliances_zll_light_49251600_level_on_off
      - switch.zw096_smart_switch_6_switch_2

automation:
  - alias: "Master Bedroom Lights on motion"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_master_bedroom
    condition:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: "disarmed"
      - condition: state
        entity_id: binary_sensor.sleepnumber_michael_angela_is_in_bed
        state: "off"
      - condition: state
        entity_id: binary_sensor.sleepnumber_michael_michael_is_in_bed
        state: "off"
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
      - condition: template
        value_template: >-
          {{ states("input_select.angela_status") != "Asleep" or
             states("input_select.michael_status") != "Asleep" }}
      - condition: template
        value_template: >-
          {{ states("input_select.angela_status") == "Home" or
             states("input_select.michael_status") == "Home" }}
      - condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - group.lights_master_bedroom

  - alias: "Master Bedroom Button 1 Pushed"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_master_bedroom_1
    action:
      - service: homeassistant.toggle
        entity_id: 
          - light.ge_appliances_zll_light_3aae1600_level_on_off


  - alias: "Master Bedroom Button 2 Pushed"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_master_bedroom_3
    action:
      - service: homeassistant.toggle
        entity_id: 
          - switch.zw096_smart_switch_6_switch_2


  - alias: "Master Bedroom Button 2 Held"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_master_bedroom_4
    action:
      - service: homeassistant.toggle
        entity_id: group.lights_master_bedroom

  - alias: "Master Bedroom Button 3 Pushed"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_master_bedroom_5
    action:
      - service: homeassistant.toggle
        entity_id: 
          - light.ge_appliances_zll_light_49251600_level_on_off

  - alias: "Laundry Door Open Turn On Light"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_3
    action:
      - entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_8c905bfe_level_light_color_on_off
        service: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}

  - alias: "Master Closet Door Open Turn On Light"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_1
    action:
      - entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_62b607fe_level_light_color_on_off
        service: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}

  - alias: "Master bath light on motion"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.motion_master_bedroom
        to: "on"
      - platform: state
        entity_id:
          - binary_sensor.motion_master_bedroom
        to: "off"
        for: "00:10:00"
    condition:
      - alias: "Light already on"
        condition: state
        entity_id:
          - light.master_bath_lights_zha_group_0x0002
        state: "off"
      - alias: "condition alias (name)"
        condition: time
        after: "22:00:00"
        before: "07:00:00"
    action:
      - choose:
        - conditions: "{{ trigger.to_state.state == 'on' }}"
          sequence:
            - service: light.turn_on
              target:
                entity_id:
                  - light.master_bath_4_level_light_color_on_off
              data:
                brightness_pct: 1
        default:
          - service: light.turn_off
            target:
              entity_id:
                - light.master_bath_4_level_light_color_on_off
