input_boolean:
  camille_med_notification_enabled:
    name: Camille Medication Notification On
    icon: mdi:pill-multiple
  camille_is_school_day:
    name: School Day
    icon: "mdi:school"


input_select:
  camille_status:
    name: "Camille's Status"
    options:
      - Home
      - School
      - Away
      - Asleep
  camille_west_day_type:
    name: "West Day Type"
    options:
      - Blue Day
      - Red Day
      - Half Day
      - No School


input_datetime:
  camille_meds_morning:
    name: "Camille's Morning Med Time"
    has_date: false
    has_time: true
  camille_meds_evening:
    name: "Camille's Evening Med Time"
    has_date: false
    has_time: true
  camille_school_start_offset:
    name: "Camille wake-up offset from school start"
    has_date: false
    has_time: true

input_text:
  camille_meds_notification:
    name: "Camille Medication Notification"

automation:

  - alias: Camille school phone to DND
    id: 87ef214b-46c6-409a-bfcd-9ced215431a2
    trigger:
      - platform: calendar
        entity_id: calendar.west_high_school
        event: start
    action:
      - alias: "Turn on dnd"
        service: script.notify_camille_dnd_total_silence

  - alias: Camille school phone DND off
    id: 1fc9e9d0-7689-41a6-8bdb-4deb13a5f66c
    trigger:
      - platform: calendar
        entity_id: calendar.west_high_school
        event: end
    action:
      - alias: "Turn off dnd"
        service: script.notify_camille_dnd_off

  - alias: Camille mark if school day
    id: 015584f8-1258-44d0-9c98-f9aa97483546
    trigger:
      - platform: time_pattern
        hours: "1"
        minutes: "/15"
    action:
      - alias: "Check if it is a school day"
        choose:
        - conditions:
            - alias: "Calendar event date is today"
              condition: template
              value_template: >-
                {% set today =  now().replace(hour=0, minute=0, second=0, microsecond=0) %}
                {% set event =  (state_attr('calendar.west_high_school', 'start_time') | as_datetime) %}
                {{ today.year == event.year and today.month == event.month
                    and today.day == event.day}}
          sequence:
            - alias: "Turn on school day boolean"
              service: homeassistant.turn_on
              target:
                entity_id: input_boolean.camille_is_school_day
        default:
          - alias: "Turn off school day boolean"
            service: homeassistant.turn_off
            target:
              entity_id: input_boolean.camille_is_school_day

  - alias: Camille Set West Day Type
    id: 40c765da-01e6-47b7-8965-5765a7dd25dc
    trigger:
      - platform: state
        entity_id: input_boolean.camille_is_school_day
    variables:
      event: "{{ state_attr('calendar.west_high_school', 'message')}}"
    action:
      - alias: "School day is on"
        choose:
        - conditions:
            - alias: "Is a school day"
              condition: state
              entity_id: input_boolean.camille_is_school_day
              state: "on"
          sequence:
            - alias: "Set west day type"
              service: input_select.select_option
              target:
                entity_id: input_select.camille_west_day_type
              data:
                option: "{{ event }}"
        default:
          - alias: "Set west day type to None"
            service: input_select.select_option
            target:
              entity_id: input_select.camille_west_day_type
            data:
              option: "No School"

  - alias: Camille wakeup before school
    id: 423b7759-8b43-47b1-9cbb-a3940df04a93
    trigger:
      - platform: calendar
        entity_id: calendar.west_high_school
        event: start
        offset: "-01:45:00"
      - platform: calendar
        entity_id: calendar.west_high_school
        event: start
        offset: "-01:30:00"
    condition:
      - alias: "Camille is home"
        condition: state
        entity_id: person.camille
        state: "home"
      - alias: "Is a school day"
        condition: state
        entity_id: input_boolean.camille_is_school_day
        state: "on"
    action:
      - alias: "Notify on camille's speaker"
        service: script.notify_camille_with_sound
        data:
          message: >-
            Good morning, Camille. Today is a {{ trigger.calendar_event.summary }}.

  - alias: "Minimote Camille Push 1"
    id: 17963bb0-262e-439d-873a-a6b148fd8f84
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_1
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - switch.z_wave_plus_power_strip_ver_2_0_5

  - alias: "Minimote Camille Hold"
    id: 5203c99e-ae5c-411e-a031-58b29f231d2d
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_camille_2
          - input_boolean.minimote_camille_4
          - input_boolean.minimote_camille_6
          - input_boolean.minimote_camille_8
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >-
            {% if is_state("input_select.camille_status", "Asleep") %}
              {% set runScript = "script.goodmorning_camille" %}
            {% elif is_state("input_select.camille_status", "Home") %}
              {% set runScript = "script.goodnight_camille" %}
            {% else %}
              {% set runScript = "automation.lights_camille_on" %}
            {% endif %}
            {{ runScript }}

  - alias: "Minimote Camille Push 2"
    id: d03bc5e4-ce23-43e7-9da2-5d5196165e1d
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_3
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - light.philips_lwb006_097e3010_level_on_off

  - alias: "Minimote Camille Push 3"
    id: 963391e8-09e0-477d-80bd-717c2c0cd7fc
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_5
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - light.ge_appliances_zll_light_1b550600_level_on_off
  
  - alias: Camille Medication Notifications On Morning
    id: a7e85b57-53c2-4aee-94d6-6fa856a4089e
    trigger:
      - platform: time
        at: input_datetime.camille_meds_morning 
    condition:
      - alias: "Is a school day"
        condition: state
        entity_id: input_boolean.camille_is_school_day
        state: "on"
    action:
      - alias: "Turn on med notifications"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camille_med_notification_enabled

  - alias: Camille Medication Notifications On Evening
    id: a1a8617e-9f47-488f-b475-b933aac643b8
    trigger:
      - platform: time
        at: input_datetime.camille_meds_evening 
    condition: []
    action:
      - alias: "Turn on med notifications"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.camille_med_notification_enabled

  - alias: Camille medication notify camille
    id: fb06daa2-4eef-4aa6-817d-be5e7452131c
    mode: restart
    trigger:
      - platform: time_pattern
        minutes: "/5"
    condition:
      - alias: "Med notification enabled"
        condition: state
        entity_id: input_boolean.camille_med_notification_enabled
        state: "on"
    action:
      - alias: "Actionable notification to camille"
        service: notify.mobile_app_sm_a326u
        data:
          message: "Time for meds"
          data: 
            actions:
              - action: "CAMILLE_MED_TAKEN"
                title: "Taken"
      - alias: "Audible notify if home"
        choose:
        - conditions:
            - alias: "Check if Camille is home"
              condition: state
              entity_id: person.camille
              state: "home"
          sequence:
            - alias: "Notify with sound"
              service: script.notify_camille_with_sound
              data:
                message: "{{ states('input_text.camille_meds_notification') }}"
      - alias: "Wait for response"
        wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: "CAMILLE_MED_TAKEN"
        timeout:
          minutes: 6
      - alias: "Turn off med notifiations"
        choose:
        - conditions: '{{ wait.trigger.event.data.action == "CAMILLE_MED_TAKEN"}}'
          sequence:
            - alias: "Turn off med notification input"
              service: input_boolean.turn_off
              target:
                entity_id: input_boolean.camille_med_notification_enabled

  - alias: Camille medication turn off with button
    id: 9541eb9c-0f70-421b-9f07-a31aaac016d5
    trigger:
      - platform: state
        entity_id: input_boolean.aqara_button_1_single
    condition:
      - alias: "Meds notification on"
        condition: state
        entity_id: input_boolean.camille_med_notification_enabled
        state: "on"
    action:
      - alias: "Turn off med notification"
        service: homeassistant.turn_off
        target:
          entity_id: input_boolean.camille_med_notification_enabled
  
  - alias: Camille medication turned off actions
    id: e1fb28a8-e855-43d1-a955-f9894df2584b
    trigger:
      - platform: state
        entity_id: input_boolean.camille_med_notification_enabled
        from: "on"
        to: "off"
    action:
      - alias: "Notify parents"
        service: script.notify_parents
        data:
          title: Camille Medications
          message: Meds taken
          alert_level: Info
  
  - alias: Camille medication notify parents if not taken
    id: 49fefe38-bc08-4756-bf7a-33004736691f
    trigger:
      - platform: state
        entity_id: input_boolean.camille_med_notification_enabled
        from: "off"
        to: "on"
        for:
          minutes: 20
    action:
      - alias: "Notify parents"
        service: script.notify_parents
        data:
          title: Camille Medications
          message: Not yet taken
          alert_level: Info

script:
  goodmorning_camille:
    alias: Goodmorning Camille
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - group.lights_bedroom_camille
      - service: homeassistant.turn_off
        data:
          entity_id: automation.wakeup_alarm_repeat_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.7

  goodnight_camille:
    alias: Good Night Camille
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_bedroom_camille
            - light.ge_appliances_zll_light_1b550600_level_on_off
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Asleep"
      - service: homeassistant.turn_on
        data:
          entity_id: automation.wakeup_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.5
      # - entity_id:
      #     - input_boolean.alarm_set_camille
      #     - input_boolean.school_day
      #   service_template: >-
      #     {% if states("sensor.weekday") == "Friday" or
      #        states("sensor.weekday") == "Saturday" %}
      #     homeassistant.turn_off
      #     {% else %}
      #     homeassistant.turn_on
      #     {% endif %}
      - service: script.daisy_goodnight
      - service: notify.notify
        data_template:
          title: "Camille"
          message: >-
            Bedtime!
            Morning alarm is {{ states("input_boolean.alarm_set_camille") }}
            {%- if is_state("input_boolean.alarm_set_camille", "on") %} for{{ " " }}
            {{- states("input_datetime.alarm_time_camille")[0:5] }}
            {%- endif %}.
