group:
  lights_whole_house:
    name: All lights in the house
    entities:
      # Living Room Lamp Left
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Metal Lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Angela's bedroom lamp
      - light.ge_appliances_zll_light_3aae1600_level_on_off
      # Camille's closet light
      - light.ge_appliances_zll_light_1b550600_level_on_off
      # Entry closet light
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Nani's Lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # Accordion Lamp
      # - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_166ca8fe_level_light_color_on_off

  lights_away:
    name: All lights when away
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # office closet
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
      # Metal lamp
      - light.ge_appliances_zll_light_49251600_level_on_off
      # Bedside lamps
      - light.smart_switch_6_2
      - light.ge_appliances_zll_light_15cd1400_level_on_off
      # Garage
      - light.master_bath_1_level_light_color_on_off
      - light.master_bath_4_level_light_color_on_off
  
  lights_alarm_home:
    name: All lights when alarm set to home
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      # office closet
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off

  lights_alarm_disabled:
    name: All lights when alarm is disable
    entities:
      # Nani's lamp
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off

  switches_whole_house:
    name: All switches in the house
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Living Room Lamp Left
      - switch.smart_switch_6
      # Michael's Lamp
      - switch.smart_switch_6_2
      # Camille's power strip
      - switch.z_wave_plus_power_strip_ver_2_0
      # - switch.z_wave_plus_power_strip_ver_2_0_2
      # - switch.z_wave_plus_power_strip_ver_2_0_3
      # - switch.z_wave_plus_power_strip_ver_2_0_4
      - switch.z_wave_plus_power_strip_ver_2_0_5
  
  switches_away:
    name: All switches when away
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # HiFi Plug
      - switch.smart_switch_6
      # Wooly
      - switch.z_wave_plus_power_strip_ver_2_0_5
  
  switches_alarm_disabled:
    name: All switches when alarm disabled
    entities:
      # TV Plug
      - switch.smart_plug_with_2_usb_ports
      # Wooly
      - switch.z_wave_plus_power_strip_ver_2_0_5

  media_whole_house:
    name: All media in the house
    entities:
      - media_player.master_bedroom_speaker
      - media_player.camille_s_room_speaker_2
      - media_player.airplay_hi_fi
      - media_player.samsung_the_frame_65
      - media_player.kitchen_display
      - media_player.office_speaker

input_select:
  home_status:
    name: Home Status
    options:
      - Normal
      - Secure
      - Service Expected
      - Service
      - Guest Expected
      - Guest
      - Sleep
      - Late Night
      - Away
      - Vacation
      - Alert
    icon: mdi:home

automation:
  - alias: Update Michael's apple watch on home status update
    id: d69c2597-15a3-4cf6-9625-75caf8b66540
    trigger:
      - platform: state
        entity_id: input_select.home_status
    action:
      - alias: "Update apple watch"
        service: notify.mobile_app_kashyyyk
        data:
          message: update_complications