group:

  christmas_lights_outdoor:
    name: Christmas Lights
    entities:
      - light.quinled_holiday_lights

  christmas_lights_indoor:
    name: Christmas Lights Indoor
    entities: []
      # - switch.smart_switch_6_2

automation:
  - alias: Christmas lights on at 6am
    id: 52f48e82-b5f6-431e-a0fe-d8d1bc064db6
    trigger:
      - platform: time
        at: "06:00:00"
    condition: []
    action:
      - alias: "Turn on all christmas lights"
        service: homeassistant.turn_on
        target:
          entity_id: 
            - group.christmas_lights_indoor
            - group.christmas_lights_outdoor

  - alias: Christmas lights off at sunrise
    id: 19b18d7d-12f8-4aef-9706-75918e56a608
    trigger:
      - platform: sun
        event: sunrise
        offset: "00:10:00"
    condition: []
    action:
      - service: homeassistant.turn_off
        target:
          entity_id:
            - group.christmas_lights_outdoor

  - alias: Christmas lights on at dusk
    trigger:
      - platform: sun
        event: sunset
        offset: "-00:30:00"
    action:
      - service: homeassistant.turn_on
        entity_id:
            - group.christmas_lights_indoor
            - group.christmas_lights_outdoor

  - alias: Christmas lights off at 1am
    trigger:
      - platform: time
        at: "01:00:00"
    action:
      - service: homeassistant.turn_off
        entity_id:
            - group.christmas_lights_indoor
            - group.christmas_lights_outdoor
