group:
  office_lights_off:
    entities:
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off
  office_lights_on:
    entities:
      - light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_989e43fe_level_light_color_on_off
  office_switches_on:
    entities:
      - switch.z_wave_plus_power_strip_ver_2_0_2
      - switch.z_wave_plus_power_strip_ver_2_0_4
  office_switches_off:
    entities:
      - switch.z_wave_plus_power_strip_ver_2_0_2
      - switch.z_wave_plus_power_strip_ver_2_0_4

automation:
  - alias: Office closet off when closed
    id: 2c09bb16-0859-4b83-bbbf-3b4aa98db6d1
    trigger:
      - platform: state
        entity_id: binary_sensor.door_windows_sensor_any_3
    condition: []
    action:
      - alias: "Turn on if sensor is open"
        service: >-
          {{ 'homeassistant.turn_on'
             if states('binary_sensor.door_windows_sensor_any_3') == 'on'
             else 'homeassistant.turn_off' }}
        target:
          entity_id: light.ikea_of_sweden_tradfri_bulb_e26_ws_opal_1000lm_50db9afe_level_light_color_on_off

  - alias: Office set to sleep
    id: 9e30d00c-345b-4436-b1a4-4b22795ec828
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Sleep"
      - platform: state
        entity_id: input_select.home_status
        to: "Away"
      - platform: state
        entity_id: input_select.home_status
        to: "Vacation"
    condition: []
    action:
      - alias: "Turn things off in office"
        service: homeassistant.turn_off
        target:
          entity_id:
            - group.office_lights_off
            - group.office_switches_off

  - alias: Office wake up
    id: 87210600-25a1-4594-8307-803577a5671a
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Normal"
      - platform: state
        entity_id: input_select.home_status
        to: "Service"
      - platform: state
        entity_id: input_select.home_status
        to: "Guest"
    condition: []
    action:
      - alias: "Turn things on in office"
        service: homeassistant.turn_on
        target:
          entity_id:
            - group.office_lights_on
            - group.office_switches_on

  - alias: G7 Play unplugged to background
    id: fc57badf-c359-4360-89d9-e13b3b02a646
    trigger:
      - platform: state
        entity_id: binary_sensor.moto_g_7_play_plugged_in
        from: "on"
        to: "off"
    condition: []
    action:
      - alias: "Send kiosk to background"
        service: button.press
        target:
          entity_id: button.moto_g_7_play_send_to_background

  - alias: G7 Play plugged to foreground
    id: 44b8a034-6906-47c5-b9d5-8277fb11df4f
    trigger:
      - platform: state
        entity_id: binary_sensor.moto_g_7_play_plugged_in
        from: "on"
        to: "off"
    condition: []
    action:
      - alias: "Send kiosk to foreground"
        service: button.press
        target:
          entity_id: button.moto_g_7_play_bring_to_foreground
      - alias: "Send kiosk to home url"
        service: button.press
        target:
          entity_id: button.moto_g_7_play_load_start_url
