input_select:
  camille_status:
    name: "Camille's Status"
    options:
      - Home
      - School
      - Away
      - Asleep

input_datetime:
  alarm_time_camille:
    name: "Set Camille's Alarm Time"
    has_date: false
    has_time: true

input_boolean:
  alarm_disable_camille:
    name: "Disable Camille's Alarm"
  alarm_set_camille:
    name: "Camille's Alarm"
    icon: mdi:alarm
  school_day:
    name: "School Day"
    icon: mdi:bus-school
  points_increment:
    name: "Increment Point"
    icon: mdi:arrow-up
  points_claim_reward:
    name: "Claim Reward"
    icon: mdi:trophy

group:
  lights_bedroom_camille:
    name: Lights in Camille's Room
    entities:
      # Grandma's Lamp
      - light.philips_lwb006_097e3010_level_on_off
      # Canopy lights
      - switch.z_wave_plus_power_strip_ver_2_0_5
      - switch.z_wave_plus_power_strip_ver_2_0
      # Camille's Closet
      # - light.ge_appliances_zll_light_1b550600_level_on_off

automation:
  - alias: Wakeup Camille
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.time.state == states.input_datetime.alarm_time_camille.state[0:5] }}
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Away" }}
      - condition: state
        entity_id: input_boolean.alarm_set_camille
        state: "on"
    action:
      - service: script.goodmorning_camille
      - service: homeassistant.turn_on
        data:
          entity_id:
            - automation.wakeup_alarm_repeat_camille
            - automation.camille_mark_awake_on_motion
      - service: media_player.play_media
        data:
          entity_id: media_player.camille_s_speaker
          media_content_id: "https://dl.dropboxusercontent.com/s/mpdyuzl5svyuxmq/Rooster%20Crowing-SoundBible.com-43612401.mp3"
          media_content_type: "music"
      - service: notify.master_ha_michael
        data:
          title: "Routines"
          message: "Wakeup Camille Ran"

  - alias: "Lights on Motion Camille's Room"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Asleep" and
             states("input_select.camille_status") != "Away" and
             states("group.lights_bedroom_camille") == "off" and
             states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: group.lights_bedroom_camille
      - service: homeassistant.turn_off
        data:
          entity_id: automation.lights_on_motion_camille_s_room
      - alias: "Turn on closet light only if door open"
        choose:
        - conditions:
            - alias: "Closet door open"
              condition: state
              entity_id: binary_sensor.door_sensor_5
              state: "off"
          sequence:
            service: homeassistant.turn_on
            data:
              entity_id: light.ge_appliances_zll_light_1b550600_level_on_off

  - alias: "Minimote Camille Push 1"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_1
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - switch.z_wave_plus_power_strip_ver_2_0_5

  - alias: "Minimote Camille Hold"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_camille_2
          - input_boolean.minimote_camille_4
          - input_boolean.minimote_camille_6
          - input_boolean.minimote_camille_8
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >-
            {% if is_state("input_select.camille_status", "Asleep") %}
              {% set runScript = "script.goodmorning_camille" %}
            {% elif is_state("input_select.camille_status", "Home") %}
              {% set runScript = "script.goodnight_camille" %}
            {% else %}
              {% set runScript = "automation.lights_camille_on" %}
            {% endif %}
            {{ runScript }}

  - alias: "Minimote Camille Push 2"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_3
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - light.philips_lwb006_097e3010_level_on_off

  - alias: "Minimote Camille Push 3"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_5
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - light.ge_appliances_zll_light_1b550600_level_on_off

  - alias: "Wakeup Alarm Repeat Camille"
    initial_state: false
    trigger:
      - platform: time_pattern
        minutes: "/2"
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.camille_s_speaker
          # media_content_id: "https://dl.dropboxusercontent.com/s/mpdyuzl5svyuxmq/Rooster%20Crowing-SoundBible.com-43612401.mp3"
          media_content_id: "https://dl.dropboxusercontent.com/s/hb2hjr9jfiztzls/train-whistle.mp3"
          media_content_type: "music"
      - delay: 0:05
      - service: media_player.play_media
        data:
          entity_id: media_player.camille_s_speaker
          media_content_id: "https://dl.dropboxusercontent.com/s/hb2hjr9jfiztzls/train-whistle.mp3"
          media_content_type: "music"

  - alias: "Camille mark awake on motion"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Asleep"
      - condition: time
        after: "06:00:00"
        before: "11:00:00"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Home"

  - alias: "Wakeup Alarm Stop Camille"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
      - platform: state
        entity_id: input_boolean.alarm_set_camille
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: automation.wakeup_alarm_repeat_camille
        state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - automation.wakeup_alarm_repeat_camille
            - input_boolean.alarm_set_camille

  - alias: "Camille turn on mark awake"
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.time.state == states.input_datetime.alarm_time_camille.state[0:5] }}
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Asleep"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - automation.camille_mark_awake_on_motion

  - alias: "Camille Time for school"
    trigger:
      - platform: time
        at: '07:35:00'
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Home"
      - condition: state
        entity_id: input_boolean.school_day
        state: "on"
    action:
      - service: scene.create
        data:
          scene_id: school_notify_before_state
          snapshot_entities:
            - light.grandma_s_lamp
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.grandma_s_lamp
            - input_boolean.school_day
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Time to catch the bus."
      - delay:
          seconds: 2
      - service: scene.turn_on
        data:
          entity_id: scene.school_notify_before_state

  - alias: "Camille take meds"
    trigger:
      - platform: state
        entity_id: input_select.camille_status
        from: "Asleep"
        to: "Home"
        for:
          minutes: 55
    condition:
      - condition: template
        value_template: >-
          {{ ((as_timestamp(utcnow()) - 
            as_timestamp(states.binary_sensor.door_sensor_5.last_changed)) / 60) 
            > 60 }}
    action: 
      - service: script.camille_meds_notify

  - alias: "Camille Brush Teeth Morning"
    trigger:
      - platform: state
        entity_id: input_select.camille_status
        from: "Asleep"
        to: "Home"
        for:
          minutes: 60
    condition:
      - condition: time
        after: "05:00:00"
        before: "11:00:00"
    action:
      - service: script.camille_brush_teeth_notify

  - alias: "Camille Brush Teeth Evening"
    trigger:
      - platform: time
        at: "20:45:00"
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Home"
    action:
      - service: script.camille_brush_teeth_notify
        
  - alias: "Camille's Closet Door Open Turn On Light"
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.door_sensor_5
    action:
      - entity_id: light.ge_appliances_zll_light_1b550600_level_on_off
        service: >-
          {% if trigger.to_state.state == "on" %}
          homeassistant.turn_on
          {% else %}
          homeassistant.turn_off
          {% endif %}

  - id: 03bc99bb-5728-4aae-98d9-17b03d9a0244
    alias: Points Button Action
    trigger:
      platform: event
      event_type: zha_event
      event_data:
        device_id: 5eb4d5579d0f2e30673144140b1fbf4a
    action:
      - variables:
          command: "{{ trigger.event.data.command }}"
      - alias: "Action on button command"
        choose:
        - conditions:
            - "{{ command == 'single' }}"
          sequence:
            service: homeassistant.turn_on
            target:
              entity_id: input_boolean.points_increment
        - conditions:
            - "{{ command == 'hold' }}"
          sequence:
            service: homeassistant.turn_on
            target:
              entity_id: input_boolean.points_claim_reward

script:
  goodmorning_camille:
    alias: Goodmorning Camille
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - group.lights_bedroom_camille
      - service: homeassistant.turn_off
        data:
          entity_id: automation.wakeup_alarm_repeat_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.7

  goodnight_camille:
    alias: Good Night Camille
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_bedroom_camille
            - light.ge_appliances_zll_light_1b550600_level_on_off
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Asleep"
      - service: homeassistant.turn_on
        data:
          entity_id: automation.wakeup_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.5
      # - entity_id:
      #     - input_boolean.alarm_set_camille
      #     - input_boolean.school_day
      #   service_template: >-
      #     {% if states("sensor.weekday") == "Friday" or
      #        states("sensor.weekday") == "Saturday" %}
      #     homeassistant.turn_off
      #     {% else %}
      #     homeassistant.turn_on
      #     {% endif %}
      - service: script.daisy_goodnight
      - service: notify.notify
        data_template:
          title: "Camille"
          message: >-
            Bedtime!
            Morning alarm is {{ states("input_boolean.alarm_set_camille") }}
            {%- if is_state("input_boolean.alarm_set_camille", "on") %} for{{ " " }}
            {{- states("input_datetime.alarm_time_camille")[0:5] }}
            {%- endif %}.

  camille_meds_notify:
    alias: Camille notify about meds
    sequence:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Did you take your meds?"

  camille_brush_teeth_notify:
    alias: Camille remind to brush teeth
    sequence:
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
            - media_player.camille_s_speaker
          message: "Camille, did you brush your teeth?"
