input_select:
  camille_status:
    name: "Camille's Status"
    options:
      - Home
      - School
      - Away
      - Asleep

input_datetime:
  alarm_time_camille:
    name: "Set Camille's Alarm Time"
    has_date: false
    has_time: true

input_boolean:
  alarm_disable_camille:
    name: "Disable Camille's Alarm"
  alarm_set_camille:
    name: "Camille's Alarm"
    icon: mdi:alarm
  school_day:
    name: "School Day"
    icon: mdi:bus-school

group:
  lights_bedroom_camille:
    name: Lights in Camille's Room
    entities:
      - light.grandma_s_lamp
      - switch.zooz_zen20_v2_0_power_strip_switch_3
      - switch.zooz_zen20_v2_0_power_strip_switch_5

automation:
  - alias: Set status for Camille
    trigger:
      - platform: state
        entity_id: person.camille
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.camille_status
          option: >-
              {% if states("person.camille") == "home" %}
              Home
              {% elif states("person.camille") == "School" %}
              School
              {% else %}
              Away
              {% endif %}

  - alias: Wakeup Camille
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.time.state == states.input_datetime.alarm_time_camille.state[0:5] }}
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Away" }}
      - condition: state
        entity_id: input_boolean.alarm_set_camille
        state: "on"
    action:
      - service: script.goodmorning_camille
      - service: homeassistant.turn_on
        data:
          entity_id:
            - automation.wakeup_alarm_repeat_camille
            - automation.camille_mark_awake_on_motion
      - service: media_player.play_media
        data:
          entity_id: media_player.camille_s_speaker
          media_content_id: "https://dl.dropboxusercontent.com/s/mpdyuzl5svyuxmq/Rooster%20Crowing-SoundBible.com-43612401.mp3"
          media_content_type: "music"
      - service: notify.mobile_app_ergisch
        data:
          title: "Routines"
          message: "Wakeup Camille Ran"

  - alias: "Lights on Motion Camille's Room"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: template
        value_template: >-
          {{ states("input_select.camille_status") != "Asleep" and
             states("input_select.camille_status") != "Away" and
             states("group.lights_bedroom_camille") == "off" and
             states("alarm_control_panel.home_alarm") == "disarmed" }}
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: group.lights_bedroom_camille

  - alias: "Minimote Camille Push 1"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_1
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
            - switch.zooz_zen20_v2_0_power_strip_switch_4
            - switch.zooz_zen20_v2_0_power_strip_switch_6

  - alias: "Minimote Camille Hold"
    trigger:
      - platform: state
        entity_id:
          - input_boolean.minimote_camille_2
          - input_boolean.minimote_camille_4
          - input_boolean.minimote_camille_6
          - input_boolean.minimote_camille_8
    action:
      - service: homeassistant.toggle
        data_template:
          entity_id: >-
            {% if is_state("input_select.camille_status", "Asleep") %}
              {% set runScript = "script.goodmorning_camille" %}
            {% elif is_state("input_select.camille_status", "Home") %}
              {% set runScript = "script.goodnight_camille" %}
            {% else %}
              {% set runScript = "automation.lights_camille_on" %}
            {% endif %}
            {{ runScript }}

  - alias: "Minimote Camille Push 2"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_3
    action:
      - service: homeassistant.toggle
        data:
          entity_id: light.grandma_s_lamp

  - alias: "Minimote Camille Push 3"
    trigger:
      - platform: state
        entity_id: input_boolean.minimote_camille_5
    action:
      - service: homeassistant.toggle
        data:
          entity_id:
          - switch.zooz_zen20_v2_0_power_strip_switch_2

  - alias: "Wakeup Alarm Repeat Camille"
    initial_state: false
    trigger:
      - platform: time_pattern
        minutes: "/2"
    action:
      - service: media_player.play_media
        data:
          entity_id: media_player.camille_s_speaker
          # media_content_id: "https://dl.dropboxusercontent.com/s/mpdyuzl5svyuxmq/Rooster%20Crowing-SoundBible.com-43612401.mp3"
          media_content_id: "https://dl.dropboxusercontent.com/s/hb2hjr9jfiztzls/train-whistle.mp3"
          media_content_type: "music"
      - delay: 0:05
      - service: media_player.play_media
        data:
          entity_id: media_player.camille_s_speaker
          media_content_id: "https://dl.dropboxusercontent.com/s/hb2hjr9jfiztzls/train-whistle.mp3"
          media_content_type: "music"

  - alias: "Camille mark awake on motion"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Asleep"
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Home"

  - alias: "Wakeup Alarm Stop Camille"
    trigger:
      - platform: state
        entity_id: binary_sensor.motion_camille_bedroom
        from: "off"
        to: "on"
      - platform: state
        entity_id: input_boolean.alarm_set_camille
        from: "on"
        to: "off"
    condition:
      - condition: state
        entity_id: automation.wakeup_alarm_repeat_camille
        state: "on"
    action:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - automation.wakeup_alarm_repeat_camille
            - input_boolean.alarm_set_camille

  - alias: "Camille turn on mark awake"
    trigger:
      - platform: template
        value_template: >-
          {{ states.sensor.time.state == states.input_datetime.alarm_time_camille.state[0:5] }}
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Asleep"
    action:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - automation.camille_mark_awake_on_motion

  - alias: "Camille Time for school"
    trigger:
      - platform: time
        at: '07:30:00'
    condition:
      - condition: state
        entity_id: input_select.camille_status
        state: "Home"
      - condition: state
        entity_id: input_boolean.school_day
        state: "on"
    action:
      - service: scene.create
        data:
          scene_id: school_notify_before_state
          snapshot_entities:
            - light.hallway_light
            - light.grandma_s_lamp
            - light.aeon_labs_zw111_nano_dimmer_level_4
      - service: homeassistant.turn_off
        data:
          entity_id:
            - light.hallway_light
            - light.grandma_s_lamp
            - light.aeon_labs_zw111_nano_dimmer_level_4
      - service: tts.google_translate_say
        data:
          entity_id:
            - media_player.living_room_display
          message: "Time to catch the bus."
      - delay:
          seconds: 2
      - service: scene.turn_on
        data:
          entity_id: scene.school_notify_before_state

script:
  goodmorning_camille:
    alias: Goodmorning Camille
    sequence:
      - service: homeassistant.turn_on
        data:
          entity_id:
            - group.lights_bedroom_camille
      - service: homeassistant.turn_off
        data:
          entity_id: automation.wakeup_alarm_repeat_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.7

  goodnight_camille:
    alias: Good Night Camille
    sequence:
      - service: homeassistant.turn_off
        data:
          entity_id:
            - group.lights_bedroom_camille
      - service: input_select.select_option
        data:
          entity_id: input_select.camille_status
          option: "Asleep"
      - service: homeassistant.turn_on
        data:
          entity_id: automation.wakeup_camille
      - service: media_player.volume_set
        data:
          entity_id: media_player.camille_s_speaker
          volume_level: 0.5
      - entity_id:
          - input_boolean.alarm_set_camille
          - input_boolean.school_day
        service_template: >-
          {% if states("sensor.weekday") == "Friday" or
             states("sensor.weekday") == "Saturday" %}
          homeassistant.turn_off
          {% else %}
          homeassistant.turn_on
          {% endif %}
      - service: notify.notify
        data_template:
          title: "Camille"
          message: >-
            Bedtime!
            Morning alarm is {{ states("input_boolean.alarm_set_camille") }}
            {%- if is_state("input_boolean.alarm_set_camille", "on") %} for{{ " " }}
            {{- states("input_datetime.alarm_time_camille")[0:5] }}
            {%- endif %}.
