group:
  switches_living_room:
    name: Living Room Switches
    entities:
      - switch.smart_switch_6
      - switch.smart_plug_with_2_usb_ports

automation:
  - alias: Living room put to sleep
    id: e9e84eeb-06ee-4244-b077-d857cd189d75
    trigger:
      - platform: template
        value_template: >-
          {{ states('input_select.home_status') in 
             ['Sleep', 'Away', 'Vacation']}}
    condition: []
    action:
      - alias: "Turn things off"
        service: homeassistant.turn_off
        target:
          entity_id:
            - group.switches_living_room

  - alias: Living room wake up
    id: f4bcf8ed-40c4-4f58-bd81-c24be8dd39e7
    trigger:
      - platform: template
        value_template: >-
          {{ states('input_select.home_status') in 
             ['Normal', 'Guest']}}
    condition: []
    action:
      - alias: "Turn things on"
        service: homeassistant.turn_on
        target:
          entity_id: group.switches_living_room