group:
  switches_living_room:
    name: Living Room Switches
    entities:
      - switch.smart_switch_6
      - switch.smart_plug_with_2_usb_ports

automation:
  - alias: Living room put to sleep
    id: e9e84eeb-06ee-4244-b077-d857cd189d75
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Sleep"
      - platform: state
        entity_id: input_select.home_status
        to: "Away"
      - platform: state
        entity_id: input_select.home_status
        to: "Vacation"
    condition: []
    action:
      - alias: "Turn things off"
        service: homeassistant.turn_off
        target:
          entity_id:
            - group.switches_living_room

  - alias: Living room wake up
    id: f4bcf8ed-40c4-4f58-bd81-c24be8dd39e7
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Normal"
      - platform: state
        entity_id: input_select.home_status
        to: "Guest"
    condition: []
    action:
      - alias: "Turn things on"
        service: homeassistant.turn_on
        target:
          entity_id: group.switches_living_room

  - alias: Front Door Open Too Long
    id: ade1de77-60e2-468d-96e8-15d146f3e7ff
    trigger:
      - platform: state
        entity_id: binary_sensor.front_door_entry
        to: "on"
        for:
          minutes: 5
    action:
      - alias: "Notify house"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Front door is open
          alert_level: Warn