sensor:
  - platform: template
    sensors:
      humidity_whole_house:
        friendly_name: Whole House Humidity
        unit_of_measurement: '%'
        value_template: >-
          {% set humidity = namespace(sum=0, count=0) %}
          {% for sensor in [
              'sensor.4_in_1_multisensor_humidity',
              'sensor.multisensor_6_humidity'
            ] %}
            {% if states(sensor)|float > 0 %}
              {% set humidity.sum = humidity.sum + (states(sensor)|float) %}
              {% set humidity.count = humidity.count + 1 %}
            {% endif %}
          {% endfor %}
          {% if humidity.count == 0 %}
            {% set humidity.count = 1 %}
          {% endif %}
          {{ (humidity.sum / humidity.count)|round(1) }}