sensor:
  - platform: template
    sensors:
      sunrise: 
        friendly_name: "Wind Bearing Description"
        value_template: >-
          {% set directionMap = {
              0: 'N',
              1: 'NE',
              2: 'E',
              3: 'SE',
              4: 'S',
              5: 'SW',
              6: 'W',
              7: 'NW',
            }
          %}
          {{ directionMap[
            (((state_attr('weather.ktys_daynight', 'wind_bearing') / 45) + 0.5) % 8) | int
            ] }}