template:
  - trigger:
    - platform: webhook
      webhook_id: d19052285ece475eb0e31ae0de91c007
    sensor:
      - name: "Air Quality Temperature"
        state: "{{ trigger.json.temperature }}"
        unit_of_measurement: °C
        device_class: temperature
      - name: "Air Quality Humidity"
        state: "{{ trigger.json.humidity }}"
        unit_of_measurement: "%"
        device_class: humidity
      - name: "Air Quality Pressure"
        state: "{{ trigger.json.pressure }}"
        unit_of_measurement: hPa
        device_class: pressure
      - name: "Air Quality Voltage"
        state: "{{ trigger.json.voltage }}"
        unit_of_measurement: V
        device_class: voltage
      - name: "Air Quality Battery Level"
        state: "{{ trigger.json.percent }}"
        unit_of_measurement: "%"
        device_class: battery
      - name: "Air Quality CO2"
        state: "{{ trigger.json.co2 }}"
        unit_of_measurement: ppm
        device_class: carbon_dioxide
      - name: "Air Quality TVOC"
        state: "{{ trigger.json.tvoc }}"
        unit_of_measurement: ppb

  - trigger:
    - platform: webhook
      webhook_id: e70fb951f53e43d8926364c74e904617
    sensor:
      - name: "Feather Particle Sensor 1.0um"
        state: "{{ trigger.json['pm10 standard'] }}"
        unit_of_measurement: µg/m³
        device_class: pm1
      - name: "Feather Particle Sensor 2.5um"
        state: "{{ trigger.json['pm25 standard'] }}"
        unit_of_measurement: µg/m³
        device_class: pm25
      - name: "Feather Particle Sensor 10um"
        state: "{{ trigger.json['pm100 standard'] }}"
        unit_of_measurement: µg/m³
        device_class: pm10

automation:
  - id: 55913ca2-3c78-4df7-91d7-c5d65ea263c0
    alias: Alert on PM levels
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.feather_particle_sensor_1_0um
          - sensor.feather_particle_sensor_2_5um
          - sensor.feather_particle_sensor_10um
        above: 40
        for: "00:00:02"
    condition: []
    action:
      - alias: "Notify on high levels"
        service: notify.master_ha_grown_ups
        data:
          title: NHT Alert
          message: High PM levels detected in bathroom
      - delay: "00:30:00"