group:
  temperature_sensors:
    name: Temperature Sensors
    entities:
      - sensor.smartthings_moisture_temperature
      - sensor.multisensor_6_air_temperature
      - sensor.4_in_1_multisensor_air_temperature
      - sensor.node_34_air_temperature
      - sensor.pir_motion_detector_air_temperature_2

input_datetime:
  thermostat_time_day:
    name: Thermostat Time Day
    has_date: false
    has_time: true
  thermostat_time_weekend_day:
    name: Thermostat Time Weekend Day
    has_date: false
    has_time: true
  thermostat_time_night:
    name: Thermostat Time Night
    has_date: false
    has_time: true

input_number:
  thermostat_target_home_low:
    name: Target Temperature Home Low
    icon: mdi:home-thermometer
    min: 50
    max: 80
    mode: box
  thermostat_target_home_high:
    name: Target Temperature Home High
    icon: mdi:home-thermometer
    min: 50
    max: 80
    mode: box
  thermostat_target_away_low:
    name: Target Temperature Away Low
    icon: mdi:home-thermometer
    min: 50
    max: 80
    mode: box
  thermostat_target_away_high:
    name: Target Temperature Away High
    icon: mdi:home-thermometer
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_cool_day:
    name: Thermostat Setpoint Cool Day
    icon: mdi:thermostat
    min: 65
    max: 80
    mode: box
  thermostat_setpoint_cool_night:
    name: Thermostat Setpoint Cool Night
    icon: mdi:thermostat
    min: 65
    max: 80
    mode: box
  thermostat_setpoint_cool_away:
    name: Thermostat Setpoint Cool Away
    icon: mdi:thermostat
    min: 65
    max: 80
    mode: box
  thermostat_setpoint_heat_day:
    name: Thermostat Setpoint Heat Day
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_heat_night:
    name: Thermostat Setpoint Heat Night
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_heat_away:
    name: Thermostat Setpoint Heat Away
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_heat_michael_only:
    name: Thermostat Setpoint Heat Michael Only
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_oool_michael_only:
    name: Thermostat Setpoint Cool Michael Only
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box

input_boolean:
  thermostat_fan_on:
    name: Thermostat Fan On
    icon: mdi:fan
  thermostat_away:
    name: Thermostat Away Mode
    icon: mdi:home-export-outline

sensor:
  - platform: template
    sensors:
      temperature_whole_house:
        friendly_name: Whole House Temperature
        unit_of_measurement: '°F'
        value_template: >-
          {% set temp = namespace(sum=0, count=0) %}
          {% for sensor in [
              'sensor.multisensor_6_air_temperature',
              'sensor.4_in_1_multisensor_air_temperature',
              'sensor.node_34_air_temperature'
            ] %}
            {% if states(sensor)|float > 0 %}
              {% set temp.sum = temp.sum + (states(sensor)|float) %}
              {% set temp.count = temp.count + 1 %}
            {% endif %}
          {% endfor %}
          {% if temp.count == 0 %}
            {% set temp.count = 1 %}
          {% endif %}
          {{ (temp.sum / temp.count)|round(1) }}
  - platform:  history_stats
    name:  "hvac_heating_run_time_1d"
    entity_id:  binary_sensor.hvac_heating
    state:  "on"
    type:  time
    end:  "{{ now() }}"
    duration:
      hours: 24
  - platform:  history_stats
    name:  "hvac_heating_run_time_7d"
    entity_id:  binary_sensor.hvac_heating
    state:  "on"
    type:  time
    end:  "{{ now() }}"
    duration:
      hours: 168
  - platform:  history_stats
    name:  "hvac_cooling_run_time_1d"
    entity_id:  binary_sensor.hvac_cooling
    state:  "on"
    type:  time
    end:  "{{ now() }}"
    duration:
      hours: 24
  - platform:  history_stats
    name:  "hvac_cooling_run_time_7d"
    entity_id:  binary_sensor.hvac_cooling
    state:  "on"
    type:  time
    end:  "{{ now() }}"
    duration:
      hours: 168

binary_sensor:
  - platform: template
    sensors:
      hvac_heating:
        friendly_name: HVAC Heating
        value_template: >-
          {{ state_attr("climate.node_34", "hvac_action") == "heating"}}
      hvac_cooling:
        friendly_name: HVAC Cooling
        value_template: >-
          {{ state_attr("climate.node_34", "hvac_action") == "cooling"}}

automation:
  - alias: Set thermostat to target temperature
    id: ff3a6f1c-8d81-44d9-a074-514f99aaaf0e
    mode: single
    trigger:
      - platform: state
        entity_id: 
          - input_number.thermostat_target_home_low
          - input_number.thermostat_target_home_high
          - input_number.thermostat_target_away_low
          - input_number.thermostat_target_away_high
        for: "00:00:05"
      - platform: state
        entity_id: input_boolean.thermostat_away
        for: "00:00:05"
      - platform: state
        entity_id: input_select.home_status
        to: "Normal"
      - platform: state
        entity_id: input_select.home_status
        to: "Secure"
      - platform: state
        entity_id: input_select.home_status
        to: "Sleep"
    condition:
      - alias: "In correct home states"
        condition: template
        value_template: >-
          {{ states('input_select.home_status') in ['Normal', 'Secure', 'Sleep'] }}
    action:
      - alias: "Set fan mode and temp variables"
        variables:
          fan_mode: >-
            {% if states("input_boolean.thermostat_fan_on") == "on" -%}
              Low
            {%- else -%}
              Auto low
            {%- endif %}
          temperature_low: >-
            {% if states("input_boolean.thermostat_away") == "on" -%}
              {{ states("input_number.thermostat_target_away_low") }}
            {%- else -%}
              {{ states("input_number.thermostat_target_home_low") }}
            {%- endif %}
          temperature_high: >-
            {% if states("input_boolean.thermostat_away") == "on" -%}
              {{ states("input_number.thermostat_target_away_high") }}
            {%- else -%}
              {{ states("input_number.thermostat_target_home_high") }}
            {%- endif %}
      - alias: "Set temps based on mode"
        choose:
        - conditions:
            - alias: "Thermostat set to heat/cool"
              condition: state
              entity_id: climate.node_34
              state: "heat_cool"
          sequence:
            - alias: "Set thremostat setpoint"
              service: script.thermostat_set_if_not_equal
              data:
                temperature: 0
                temperature_low: "{{ temperature_low | int }}"
                temperature_high: "{{ temperature_high | int }}"
        - conditions:
            - alias: "Thermostat set to heat"
              condition: state
              entity_id: climate.node_34
              state: "heat"
          sequence:
            - alias: "Set thremostat setpoint"
              service: script.thermostat_set_if_not_equal
              data:
                temperature: "{{ temperature_low | int }}"
                temperature_low: 0
                temperature_high: 0
        - conditions:
            - alias: "Thermostat set to cool"
              condition: state
              entity_id: climate.node_34
              state: "cool"
          sequence:
            - alias: "Set thremostat setpoint"
              service: script.thermostat_set_if_not_equal
              data:
                temperature: "{{ temperature_high | int }}"
                temperature_low: 0
                temperature_high: 0
      - alias: "Set fan"
        service: climate.set_fan_mode
        target:
          entity_id: climate.node_34
        data:
          fan_mode: "{{ fan_mode }}"
      - delay: "00:00:10"

  - alias: Thermostat away mode on vacation
    id: a5d567e6-7f55-4a8e-bec5-4942dfe8395b
    trigger:
      - platform: state
        entity_id: input_select.home_status
        to: "Vaction"
    condition: []
    action:
      - alias: "Set thermostat to away mode"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.thermostat_away
  
  - alias: Thermostat away mode off on status change
    id: 62904373-0f1e-4b0f-aa18-a829b81f30fa
    trigger:
      - platform: state
        entity_id: input_select.home_status
        from: "Vaction"
    condition:
      - alias: "Home in away mode"
        condition: state
        entity_id: input_boolean.thermostat_away
        state: "on"
      - "{{ states('input_select.home_status' != 'Alert')}}"
    action:
      - alias: "Set thermostat to home mode"
        service: input_boolean.turn_off
        target:
          entity_id: input_boolean.thermostat_away

  - alias: Thermostat Set Target Night
    id: eac65317-2910-4553-811a-92795aaa6cc7
    trigger:
      - platform: time
        at: input_datetime.thermostat_time_night
    condition: []
    action:
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_low
        data:
          value: "{{ states('input_number.thermostat_setpoint_heat_night')}}"
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_high
        data:
          value: "{{ states('input_number.thermostat_setpoint_cool_night')}}"

  - alias: Thermostat Set Target Workday
    id: 1dd4b108-62d8-4a37-bc79-db7401a53565
    trigger:
      - platform: time
        at: input_datetime.thermostat_time_day
      - platform: state
        entity_id: sensor.location_michael_home_alone
        from: "True"
        to: "False"
    condition:
      - alias: "Is a workday"
        condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
      - alias: "Not in night routine"
        condition: time
        after: input_datetime.thermostat_time_day
        before: input_datetime.thermostat_time_night
    action:
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_low
        data:
          value: "{{ states('input_number.thermostat_setpoint_heat_day')}}"
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_high
        data:
          value: "{{states('input_number.thermostat_setpoint_cool_day')}}"

  - alias: Thermostat Set Target Non Workday
    id: f4b02269-3f4b-48df-9748-f5dc3399fd46
    trigger:
      - platform: time
        at: input_datetime.thermostat_time_weekend_day
      - platform: state
        entity_id: sensor.location_michael_home_alone
        from: "True"
        to: "False"
    condition:
      - alias: "Is a workday"
        condition: state
        entity_id: binary_sensor.workday_sensor
        state: "off"
      - alias: "Not in night routine"
        condition: time
        after: input_datetime.thermostat_time_weekend_day
        before: input_datetime.thermostat_time_night
    action:
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_low
        data:
          value: "{{ states('input_number.thermostat_setpoint_heat_day')}}"
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_high
        data:
          value: "{{states('input_number.thermostat_setpoint_cool_day')}}"

  - alias: Thermostat Set Target Michael Only
    id: 72d7cd8e-59bc-4afa-af29-24e30e8b7f9e
    trigger:
      - platform: state
        entity_id: sensor.location_michael_home_alone
        from: "False"
        to: "True"
    condition:
      - alias: "Is a workday"
        condition: state
        entity_id: binary_sensor.workday_sensor
        state: "off"
      - alias: "Not in night routine"
        condition: time
        after: input_datetime.thermostat_time_day
        before: input_datetime.thermostat_time_night
    action:
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_low
        data:
          value: "{{ states('input_number.thermostat_setpoint_heat_day')}}"
      - alias: "Set thremostat target"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_home_high
        data:
          value: "{{states('input_number.thermostat_setpoint_cool_day')}}"

  - alias: Thermostat Set Target Away
    id: 70c40727-cc53-4093-a344-e3bad64c212b
    trigger:
      - platform: state
        entity_id: input_boolean.thermostat_away
        from: "off"
        to: "on"
    condition: []
    action:
      - alias: "Set thremostat target away"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_away_low
        data:
          value: "{{ states('input_number.thermostat_setpoint_heat_away')}}"
      - alias: "Set thremostat target away"
        service: input_number.set_value
        target:
          entity_id: input_number.thermostat_target_away_high
        data:
          value: "{{states('input_number.thermostat_setpoint_cool_away')}}"

  - alias: Temperature alert garage
    id: eafd6b87-9319-4640-b3c8-befea8eaebea
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.pir_motion_detector_air_temperature
        below: 45
        for: "00:15:00"
    action:
      - alias: "Notify parents"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Garage Temperature Low
          alert_level: Warn

  - alias: Thermostat heat vent check
    id: 95e3f418-ed53-4377-a9de-7c1bcb92bf09
    trigger:
      - platform: state
        entity_id: climate.node_34
        attribute: hvac_action
        from: idle
        to: heating
        for: "00:05:00"
      - platform: numeric_state
        entity_id: sensor.vent_temperature
        below: 90
        for: "00:00:15"
    condition:
      - alias: "Thermostat is heating"
        condition: state
        entity_id: climate.node_34
        attribute: hvac_action
        state: "heating"
      - alias: "Vent check is not hot enough"
        condition: numeric_state
        entity_id: sensor.vent_temperature
        below: 90
    action:
      - alias: "turn heat off"
        service: climate.set_hvac_mode
        target:
          entity_id: climate.node_34
        data:
          hvac_mode: "off"
      - alias: "turn heat on"
        service: climate.set_hvac_mode
        target:
          entity_id: climate.node_34
        data:
          hvac_mode: heat
      - alias: "Warn adults"
        service: script.notify_michael
        data:
          title: Taliluna Alert
          message: Vent Check Heat Reset
          alert_level: Warn

  - alias: Thermostat not heating alert
    id: 7244608a-f75d-4976-9ea5-6b33b9509d19
    trigger:
      - platform: state
        entity_id: sensor.node_34_air_temperature
    condition:
      - alias: "Thermostat set to heating"
        condition: state
        entity_id: climate.node_34
        attribute: hvac_action
        state: "heating"
        for: "00:02:00"
      - alias: "check if temp is lower than before"
        condition: template
        value_template: >-
          {{ trigger.to_state.state < trigger.from_state.state }}
    action:
      - alias: "Warn adults"
        service: script.notify_michael
        data:
          title: Taliluna Alert
          message: Temperature drop while heating
          alert_level: Warn

  - alias: Thermostat not cooling alert
    id: 1f2150d2-1a4e-4208-b41d-f64015978299
    trigger:
      - platform: state
        entity_id: sensor.node_34_air_temperature
    condition: 
      - alias: "Thermostat set to cooling"
        condition: state
        entity_id: climate.node_34
        attribute: hvac_action
        state: "cooling"
        for: "00:02:00"
      - alias: "check if temp is higher than before"
        condition: template
        value_template: >-
          {{ trigger.to_state.state > trigger.from_state.state }}
    action:
      - alias: "Warn adults"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Temperature drop while heating
          alert_level: Warn

script:
  thermostat_set_if_not_equal:
    alias: "Thermostat Set If Not Equal"
    fields:
      temperature:
        description: Thermostat Temp in Heat or Cool Mode
        example: "70"
        default: 0
      temperature_low:
        description: Thermostat Low Setpoint
        example: "68"
        default: 0
      temperature_high:
        description: Thermostat High Setpoint
        example: "72"
        default: 0
    sequence:
      - alias: "Set Temp if not already set"
        choose:
        - conditions:
            - alias: "temperature provided and not already set"
              condition: template
              value_template: >-
                {{ temperature != 0 and 
                   state_attr("climate.node_34", "temperature") != temperature }}
          sequence:
            - alias: "Set thermostat temp"
              service: climate.set_temperature
              target:
                entity_id: climate.node_34
              data:
                temperature: '{{ temperature | int }}'
        - conditions:
            - alias: "high/low targets provided and not already set"
              condition: template
              value_template: >-
                {{ temperature_low != 0 and temperature_high != 0 and
                   ( state_attr("climate.node_34", "target_temp_low") != temperature_low or 
                     state_attr("climate.node_34", "target_temp_high") != temperature_high ) }}
          sequence:
            - alias: "Set thermostat target temp"
              service: climate.set_temperature
              target:
                entity_id: climate.node_34
              data:
                target_temp_low: '{{ temperature_low | int }}'
                target_temp_high: '{{ temperature_high | int }}'
