group:
  temperature_sensors:
    name: Temperature Sensors
    entities:
      - sensor.smartthings_moisture_temperature
      - sensor.multisensor_6_air_temperature
      - sensor.4_in_1_multisensor_air_temperature
      - sensor.z_wave_plus_thermostat_air_temperature
      - sensor.pir_motion_detector_air_temperature_2

input_datetime:
  thermostat_time_day:
    name: Thermostat Time Day
    has_date: false
    has_time: true
  thermostat_time_weekend_day:
    name: Thermostat Time Weekend Day
    has_date: false
    has_time: true
  thermostat_time_night:
    name: Thermostat Time Night
    has_date: false
    has_time: true

input_number:
  thermostat_target_home:
    name: Thermostat Target Temperature Home
    icon: mdi:home-thermometer
    min: 50
    max: 80
    mode: box
  thermostat_target_away:
    name: Thermostat Target Temperature Away
    icon: mdi:home-thermometer
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_cool_day:
    name: Thermostat Setpoint Cool Day
    icon: mdi:thermostat
    min: 65
    max: 80
    mode: box
  thermostat_setpoint_cool_night:
    name: Thermostat Setpoint Cool Night
    icon: mdi:thermostat
    min: 65
    max: 80
    mode: box
  thermostat_setpoint_cool_away:
    name: Thermostat Setpoint Cool Away
    icon: mdi:thermostat
    min: 65
    max: 80
    mode: box
  thermostat_setpoint_heat_day:
    name: Thermostat Setpoint Heat Day
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_heat_night:
    name: Thermostat Setpoint Heat Night
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box
  thermostat_setpoint_heat_away:
    name: Thermostat Setpoint Heat Away
    icon: mdi:thermostat
    min: 50
    max: 80
    mode: box

input_boolean:
  thermostat_fan_on:
    name: Thermostat Fan On
    icon: mdi:fan
  thermostat_away:
    name: Thermostat Away Mode
    icon: mdi:home-export-outline

sensor:
  - platform: template
    sensors:
      temperature_whole_house:
        friendly_name: Whole House Temperature
        unit_of_measurement: '°F'
        value_template: >-
          {% set temp = namespace(sum=0, count=0) %}
          {% for sensor in [
              'sensor.smartthings_moisture_temperature',
              'sensor.multisensor_6_air_temperature',
              'sensor.4_in_1_multisensor_air_temperature',
              'sensor.z_wave_plus_thermostat_air_temperature'
            ] %}
            {% if states(sensor)|float > 0 %}
              {% set temp.sum = temp.sum + (states(sensor)|float) %}
              {% set temp.count = temp.count + 1 %}
            {% endif %}
          {% endfor %}
          {% if temp.count == 0 %}
            {% set temp.count = 1 %}
          {% endif %}
          {{ (temp.sum / temp.count)|round(1) }}

automation:
  - alias: Set thermostat to target temperature
    id: ff3a6f1c-8d81-44d9-a074-514f99aaaf0e
    trigger:
      - platform: state
        entity_id: 
          - input_number.thermostat_target_home
          - input_number.thermostat_target_away
      - platform: state
        entity_id: input_boolean.thermostat_away
    condition:
      - alias: "Not in guest mode"
        condition: state
        entity_id: input_boolean.guest_mode
        state: "off"
    action:
      - alias: "Set fan mode and temp variable"
        variables:
          fan_mode: >-
            {% if states("input_boolean.thermostat_fan_on") == "on" -%}
              Low
            {%- else -%}
              Auto low
            {%- endif %}
          temperature: >-
            {% if states("input_boolean.thermostat_away") == "on" -%}
              {{ states("input_number.thermostat_target_away") }}
            {%- else -%}
              {{ states("input_number.thermostat_target_home") }}
            {%- endif %}
      - alias: "Set thremostat setpoint"
        ## TODO This should only run if setpoint is different than target
        service: climate.set_temperature
        target:
          entity_id: climate.z_wave_plus_thermostat
        data:
          temperature: "{{ temperature | int }}"
      - alias: "Set fan"
        service: climate.set_fan_mode
        target:
          entity_id: climate.z_wave_plus_thermostat
        data:
          fan_mode: "{{ fan_mode }}"

  - alias: Set thermostat away mode from alarm status
    id: a5d567e6-7f55-4a8e-bec5-4942dfe8395b
    trigger:
      - platform: state
        entity_id: alarm_control_panel.home_alarm
        to: "armed_away"
    condition: []
    action:
      - alias: "Set thermostat to away mode"
        service: input_boolean.turn_on
        target:
          entity_id: input_boolean.thermostat_away

  - alias: Set Thermostat Night
    id: eac65317-2910-4553-811a-92795aaa6cc7
    trigger:
      - platform: time
        at: input_datetime.thermostat_time_night
    condition: []
    action:
      - alias: "Heat or cool"
        choose:
        - conditions:
            - alias: "Heat is on"
              condition: state
              entity_id: climate.z_wave_plus_thermostat
              state: "heat"
          sequence:
            - alias: "Set thremostat target"
              service: input_number.set_value
              target:
                entity_id: input_number.thermostat_target_home
              data:
                value: "{{ states('input_number.thermostat_setpoint_heat_night')}}"
        default:
          - alias: "Set thrermostat target temperature"
            service: input_number.set_value
            target:
              entity_id: input_number.thermostat_target_temperature
            data:
              value: "{{states('input_number.thermostat_setpoint_cool_night')}}"

  - alias: Set Thermostat Workday
    id: 1dd4b108-62d8-4a37-bc79-db7401a53565
    trigger:
      - platform: time
        at: input_datetime.thermostat_time_day
    condition:
      - alias: "Is a workday"
        condition: state
        entity_id: binary_sensor.workday_sensor
        state: "on"
    action:
      - alias: "Heat or cool"
        choose:
        - conditions:
            - alias: "Heat is on"
              condition: state
              entity_id: climate.z_wave_plus_thermostat
              state: "heat"
          sequence:
            - alias: "Set thremostat target"
              service: input_number.set_value
              target:
                entity_id: input_number.thermostat_target_home
              data:
                value: "{{ states('input_number.thermostat_setpoint_heat_day')}}"
        default:
          - alias: "Set thremostat target"
            service: input_number.set_value
            target:
              entity_id: input_number.thermostat_target_home
            data:
              value: "{{states('input_number.thermostat_setpoint_cool_day')}}"

  - alias: Set Thermostat Non Workday
    id: f4b02269-3f4b-48df-9748-f5dc3399fd46
    trigger:
      - platform: time
        at: input_datetime.thermostat_time_weekend_day
    condition:
      - alias: "Is a workday"
        condition: state
        entity_id: binary_sensor.workday_sensor
        state: "off"
    action:
      - alias: "Heat or cool"
        choose:
        - conditions:
            - alias: "Heat is on"
              condition: state
              entity_id: climate.z_wave_plus_thermostat
              state: "heat"
          sequence:
            - alias: "Set thremostat target"
              service: input_number.set_value
              target:
                entity_id: input_number.thermostat_target_home
              data:
                value: "{{ states('input_number.thermostat_setpoint_heat_day')}}"
        default:
          - alias: "Set thremostat target"
            service: input_number.set_value
            target:
              entity_id: input_number.thermostat_target_home
            data:
              value: "{{states('input_number.thermostat_setpoint_cool_day')}}"

  - alias: Set Thermostat Away
    id: 70c40727-cc53-4093-a344-e3bad64c212b
    trigger:
      - platform: state
        entity_id: climate.z_wave_plus_thermostat
        to: "heat"
      - platform: state
        entity_id: climate.z_wave_plus_thermostat
        to: "cool"
      - platform: state
        entity_id: 
          - input_number.thermostat_setpoint_heat_away
          - input_number.thermostat_setpoint_cool_away
    condition: []
    action:
      - alias: "Heat or cool"
        choose:
        - conditions:
            - alias: "Heat is on"
              condition: state
              entity_id: climate.z_wave_plus_thermostat
              state: "heat"
          sequence:
            - alias: "Set thremostat target away"
              service: input_number.set_value
              target:
                entity_id: input_number.thermostat_target_away
              data:
                temperature: "{{ states('input_number.thermostat_setpoint_heat_away')}}"
        default:
          - alias: "Set thremostat target away"
            service: input_number.set_value
            target:
              entity_id: input_number.thermostat_target_away
            data:
              temperature: "{{states('input_number.thermostat_setpoint_cool_away')}}"

  - alias: Temperature alert garage
    id: eafd6b87-9319-4640-b3c8-befea8eaebea
    trigger:
      - platform: numeric_state
        entity_id: 
          - sensor.pir_motion_detector_air_temperature
        below: 45
        for: "00:15:00"
    action:
      - alias: "Notify parents"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Garage Temperature Low
          alert_level: Warn

  - id: 95e3f418-ed53-4377-a9de-7c1bcb92bf09
    alias: Thermostat heat vent check
    trigger:
      - platform: state
        entity_id: climate.z_wave_plus_thermostat
        attribute: hvac_action
        from: idle
        to: heating
        for: "00:01:00"
    condition: []
    action:
      - alias: "Warn adults"
        service: script.notify_michale
        data:
          title: Taliluna Alert
          message: Vent Check Test
          alert_level: Warn

  - id: 7244608a-f75d-4976-9ea5-6b33b9509d19
    alias: Thermostat not heating alert
    trigger:
      - platform: state
        entity_id: sensor.z_wave_plus_thermostat_air_temperature
    condition: []
      # - alias: "Thermostat set to heating"
      #   condition: state
      #   entity_id: climate.z_wave_plus_thermostat
      #   attribute: hvac_action
      #   state: "heating"
      #   for: "00:02:00"
      # - alias: "check if temp is lower than before"
      #   condition: template
      #   value_template: >-
      #     {{ trigger.to_state.state < trigger.from_state.state }}
    action:
      # - alias: "turn heat off"
      #   service: climate.set_hvac_mode
      #   target:
      #     entity_id: climate.z_wave_plus_thermostat
      #   data:
      #     hvac_mode: "off"
      # - alias: "turn heat on"
      #   service: climate.set_hvac_mode
      #   target:
      #     entity_id: climate.z_wave_plus_thermostat
      #   data:
      #     hvac_mode: heat
      - alias: "Warn adults"
        service: script.notify_michale
        data:
          title: Taliluna Alert
          message: Temperature drop while heating
          alert_level: Warn

  - id: 1f2150d2-1a4e-4208-b41d-f64015978299
    alias: Thermostat not cooling alert
    trigger:
      - platform: state
        entity_id: sensor.z_wave_plus_thermostat_air_temperature
    condition: 
      - alias: "Thermostat set to cooling"
        condition: state
        entity_id: climate.z_wave_plus_thermostat
        attribute: hvac_action
        state: "cooling"
        for: "00:02:00"
      - alias: "check if temp is higher than before"
        condition: template
        value_template: >-
          {{ trigger.to_state.state > trigger.from_state.state }}
    action:
      - alias: "Warn adults"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Temperature drop while heating
          alert_level: Warn

  # - alias: Fan default by temperature
  #   id: dd58fd8b-ab58-4c26-a574-4429de6a8940
  #   trigger:
  #     - platform: numeric_state
  #       entity_id: sensor.z_wave_plus_thermostat_air_temperature
  #     - platform: numeric_state
  #       entity_id: sensor.z_wave_plus_thermostat_air_temperature
  #       attribute: temperature
  #   condition: []
  #   action:
