sensor:
  - platform: template
    sensors:
      wind_bearing_description: 
        friendly_name: "Wind Bearing Description"
        icon_template: >-
          {% set iconMap = {
              0: 'mdi:arrow-down',
              1: 'mdi:arrow-bottom-left',
              2: 'mdi:arrow-left',
              3: 'mdi:arrow-top-left',
              4: 'mdi:arrow-up',
              5: 'mdi:arrow-top-right',
              6: 'mdi:arrow-right',
              7: 'mdi:arrow-bottom-right',
            }
          %}
          {{ iconMap[
            (((state_attr('weather.ktys_daynight', 'wind_bearing') / 45) + 0.5) % 8) | int
            ] }}
        value_template: >-
          {% set directionMap = {
              0: 'N',
              1: 'NE',
              2: 'E',
              3: 'SE',
              4: 'S',
              5: 'SW',
              6: 'W',
              7: 'NW',
            }
          %}
          {{ directionMap[
            (((state_attr('weather.ktys_daynight', 'wind_bearing') / 45) + 0.5) % 8) | int
            ] }}