# Small Bath Remote
automation:
  - alias: "Bathroom Lights IKEA Button"
    mode: queued
    max_exceeded: silent
    variables:
      force_brightness: false
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_id: 7b31d0bae7a4a338844bb3a73d420c44

    action:
      - variables:
          command: "{{ trigger.event.data.command }}"
          cluster_id: "{{ trigger.event.data.cluster_id }}"
          endpoint_id: "{{ trigger.event.data.endpoint_id }}"
          args: "{{ trigger.event.data.args }}"
      - choose:
          - conditions:
              - "{{ command == 'toggle' }}"
              - "{{ cluster_id == 6 }}"
              - "{{ endpoint_id == 1 }}"
            sequence:
              - choose:
                  - conditions: "{{ force_brightness }}"
                    sequence:
                      - service: light.toggle
                        target: 
                          entity_id: light.bathroom_lights_zha_group_0x0003
                        data:
                          transition: 1
                          brightness_pct: 100
                default:
                  - service: light.toggle
                    target: 
                      entity_id: light.bathroom_lights_zha_group_0x0003
                    data:
                      transition: 1

          - conditions:
              - "{{ command == 'step_with_on_off' }}"
              - "{{ cluster_id == 8 }}"
              - "{{ endpoint_id == 1 }}"
              - "{{ args == [0, 43, 5] }}"
            sequence:
              - choose:
                  - conditions:
                      - alias: "Left Light Off"
                        condition: state
                        entity_id: light.bathroom_light_1_level_light_color_on_off
                        state: "off"
                      - alias: "Right Light On"
                        condition: state
                        entity_id: light.bathroom_light_4_level_light_color_on_off
                        state: "on"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: light.master_bath_lights_zha_group_0x0002
                        data:
                          brightness: 255
                  - conditions:
                      - alias: "Brightness greater than 75%"
                        condition: numeric_state
                        entity_id: light.bathroom_lights_zha_group_0x0003
                        attribute: brightness
                        above: 192
                    sequence:
                      - service: light.turn_on
                        target: 
                          entity_id: light.bathroom_lights_zha_group_0x0003
                        data:
                          brightness: 255
                default:
                  - service: light.turn_on
                    target: 
                      entity_id: light.bathroom_lights_zha_group_0x0003
                    data:
                      brightness_step: 64
                      transition: 1

          # - conditions:
          #     - "{{ command == 'move_with_on_off' }}"
          #     - "{{ cluster_id == 8 }}"
          #     - "{{ endpoint_id == 1 }}"
          #     - "{{ args == [0, 84] }}"
          #   sequence:
          #     - repeat:
          #         count: 10
          #         sequence:
          #           - service: light.turn_on
          #             target:
          #               entity_id: light.bathroom_lights_zha_group_0x0003
          #             data:
          #               brightness_step_pct: 10
          #               transition: 1
          #           - delay: 1

          - conditions:
              - "{{ command == 'step' }}"
              - "{{ cluster_id == 8 }}"
              - "{{ endpoint_id == 1 }}"
              - "{{ args == [1, 43, 5] }}"
            sequence:
              - choose:
                  - conditions:
                      - alias: "Brightness lower than 25%"
                        condition: numeric_state
                        entity_id: light.bathroom_lights_zha_group_0x0003
                        attribute: brightness
                        below: 64
                    sequence:
                      - service: light.turn_on
                        target: 
                          entity_id: light.bathroom_lights_zha_group_0x0003
                        data:
                          brightness: 1
                default:
                  - service: light.turn_on
                    target: 
                      entity_id: light.bathroom_lights_zha_group_0x0003
                    data:
                      brightness_step: -64
                      transition: 1

          # - conditions:
          #     - "{{ command == 'move' }}"
          #     - "{{ cluster_id == 8 }}"
          #     - "{{ endpoint_id == 1 }}"
          #     - "{{ args == [1, 84] }}"
          #   sequence:
          #     - repeat:
          #         count: 10
          #         sequence:
          #           - service: light.turn_on
          #             target: 
          #               entity_id: light.bathroom_lights_zha_group_0x0003
          #             data:
          #               brightness_step_pct: -10
          #               transition: 1
          #           - delay: 1

          # - conditions:
          #     - "{{ command == 'press' }}"
          #     - "{{ cluster_id == 5 }}"
          #     - "{{ endpoint_id == 1 }}"
          #     - "{{ args == [257, 13, 0] }}"
          #   sequence:
          #     - service: light.turn_on
          #       target:
          #         entity_id: light.bathroom_lights_zha_group_0x0003
          #       data:
          #         color_temp: "{{ state_attr('light.master_bath_1_level_light_color_on_off', 'color_temp')|int + 10}}"

          # - conditions:
          #     - "{{ command == 'hold' }}"
          #     - "{{ cluster_id == 5 }}"
          #     - "{{ endpoint_id == 1 }}"
          #     - "{{ args == [3329, 0] }}"
          #   sequence: !input button_left_long

          # - conditions:
          #     - "{{ command == 'press' }}"
          #     - "{{ cluster_id == 5 }}"
          #     - "{{ endpoint_id == 1 }}"
          #     - "{{ args == [256, 13, 0] }}"
          #   sequence: !input button_right_short

          # - conditions:
          #     - "{{ command == 'hold' }}"
          #     - "{{ cluster_id == 5 }}"
          #     - "{{ endpoint_id == 1 }}"
          #     - "{{ args == [3328, 0] }}"
          #   sequence: !input button_right_long