automation:
  - id: bbc82e4a-968e-4a36-9f52-6c7396d5f38e
    alias: iOS Action Disarm Taliluna
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          # source may be one of:
          # - appShortcut
          # - preview
          # - siriShortcut
          # - urlHandler
          # - watch
          # - widget
          actionID: 8A95C27F-C66B-42BD-8EBF-7C46F65C79AE
          actionName: Alarm Disarm
          sourceDeviceID: scarif
          sourceDeviceName: Scarif
          sourceDevicePermanentID: AC0F3FB2-95FB-4864-923E-0C6E514FF4D9
          # triggerSource: preview
    condition: []
    action:
      - if: >-
          {{states("alarm_control_panel.simplisafe") != "disarmed"}}
        then:
          - alias: "disarm the alarm"
            service: alarm_control_panel.alarm_disarm
            target:
              entity_id: alarm_control_panel.simplisafe
  
  - id: 244addbe-5c89-4cf2-8a8b-2fc948c1a79f
    alias: iOS Action Arm Taliluna
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          # source may be one of:
          # - appShortcut
          # - preview
          # - siriShortcut
          # - urlHandler
          # - watch
          # - widget
          actionID: BDE1ABD9-79F1-42BA-9451-0A0A994CBADB
          actionName: Arm Alarm
          sourceDeviceID: scarif
          sourceDeviceName: Scarif
          sourceDevicePermanentID: AC0F3FB2-95FB-4864-923E-0C6E514FF4D9
          # triggerSource: preview
    condition: []
    action:
      - if: >-
          {{states("alarm_control_panel.simplisafe") == "disarmed"}}
        then:
          - alias: "arm the alarm"
            service: alarm_control_panel.alarm_arm_away
            target:
              entity_id: alarm_control_panel.simplisafe

  - id: 9aa64cee-dfe2-40b4-b0f7-01c2e8b36f82
    alias: iOS Action Open Close Garage
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          # source may be one of:
          # - appShortcut
          # - preview
          # - siriShortcut
          # - urlHandler
          # - watch
          # - widget
          actionID: 45730500-9304-4F78-9E57-DFC254F061F7
          actionName: Tali Garage
          sourceDeviceID: scarif
          sourceDeviceName: Scarif
          sourceDevicePermanentID: AC0F3FB2-95FB-4864-923E-0C6E514FF4D9
          # triggerSource: preview
    condition: []
    action:
      - alias: "Unlock Garage Door"
        service: homeassistant.turn_on
        target:
          entity_id: switch.multirelay_2

  - id: 414e4642-1cf8-4af7-97bc-01fe7fcb09b6
    alias: iOS Actions Set home to sleep
    trigger:
      - platform: event
        event_type: ios.action_fired
        event_data:
          # source may be one of:
          # - appShortcut
          # - preview
          # - siriShortcut
          # - urlHandler
          # - watch
          # - widget
          actionID: 46560507-AC10-49C3-9333-876A432C37AE
          actionName: Tali Sleep
          sourceDeviceID: scarif
          sourceDeviceName: Scarif
          sourceDevicePermanentID: AC0F3FB2-95FB-4864-923E-0C6E514FF4D9
          # triggerSource: preview
    condition: 
      - "{{ not states('input_select.home_status') in ['Guest', 'Sleep']}}"
    action:
      - alias: "Set home status to sleep"
        service: input_select.select_option
        target:
          entity_id: input_select.home_status
        data:
          option: "Sleep"
