#Living room remote
automation:
  - alias: "Living Room Ikea Button"
    id: "86096adc-328b-4435-a5ec-882adbe0da81"
    mode: queued
    max_exceeded: silent
    trigger:
      - platform: event
        event_type: zha_event
        event_data:
          device_id: df652b4f32fb44e7b43f0cd53db701c5
    action:
      - variables:
          command: "{{ trigger.event.data.command }}"
          cluster_id: "{{ trigger.event.data.cluster_id }}"
          endpoint_id: "{{ trigger.event.data.endpoint_id }}"
          args: "{{ trigger.event.data.args }}"
      - choose:
          - conditions:
              - "{{ command == 'toggle' }}"
              - "{{ cluster_id == 6 }}"
              - "{{ endpoint_id == 1 }}"
            sequence:
              - choose:
                - conditions:
                  - alias: "Lights are off"
                    condition: state
                    entity_id: group.lights_switches_living_room
                    state: "off"
                  sequence:
                  - service: homeassistant.turn_on
                    target:
                      entity_id:
                        - group.lights_switches_living_room
                        - switch.smart_plug_with_2_usb_ports
                default:
                - service: homeassistant.turn_off
                  target:
                    entity_id:
                      - group.lights_switches_living_room

          # Brightness Up pressed
          - conditions:
              - "{{ command == 'step_with_on_off' }}"
              - "{{ cluster_id == 8 }}"
              - "{{ endpoint_id == 1 }}"
              # - "{{ args == [0, 43, 5] }}"
            sequence:
              - choose:
                  - conditions:
                    - >
                      {{ (expand('group.lights_living_room') | 
                        map(attribute='attributes.brightness') | 
                        list | min | int) > 191 }}
                    sequence:
                      - service: light.turn_on
                        target: 
                          entity_id: group.lights_living_room
                        data:
                          brightness: 255
                default:
                  - service: light.turn_on
                    target: 
                      entity_id: group.lights_living_room
                    data:
                      brightness_step: 64
                      transition: 1

          # Brightness Down pressed
          - conditions:
              - "{{ command == 'step' }}"
              - "{{ cluster_id == 8 }}"
              - "{{ endpoint_id == 1 }}"
              # - "{{ args == [1, 43, 5] }}"
            sequence:
              - choose:
                  - conditions:
                    - >
                      {{ (expand('group.lights_living_room') | 
                        map(attribute='attributes.brightness') | 
                        list | min | int) < 65 }}
                    sequence:
                      - service: light.turn_on
                        target: 
                          entity_id: group.lights_living_room
                        data:
                          brightness: 1
                          transition: 1
                default:
                  - service: light.turn_on
                    target: 
                      entity_id: group.lights_living_room
                    data:
                      brightness_step: -64
                      transition: 1
          
          # Arrow Left pressed
          - conditions:
              - "{{ command == 'press' }}"
              - "{{ cluster_id == 5 }}"
              - "{{ endpoint_id == 1 }}"
              # - "{{ args == [257, 13, 0] }}"
            sequence:
              - service: media_player.volume_down
                target:
                  entity_id: media_player.living_room_tv

          # Arrow Left pressed
          - conditions:
              - "{{ command == 'press' }}"
              - "{{ cluster_id == 5 }}"
              - "{{ endpoint_id == 1 }}"
              # - "{{ args == [256, 13, 0] }}"
            sequence:
              - service: media_player.volume_up
                target:
                  entity_id: media_player.living_room_tv
