# Node 14
automation:
  - alias: Minimote Master Bedroom
    id: "8264c12f-69dc-412d-9ce8-f745a13f6ad6"
    trigger:
      - platform: event
        event_type: zwave_js_value_notification
        event_data:
          node_id: 14
          home_id: 3996165589
    action:
      - alias: "Action on button pressed"
        choose:
          - conditions:
            - "{{trigger.event.data.value|int == 3}}"
            sequence:
            - service: homeassistant.toggle
              target:
                entity_id:
                  - lock.garage_door
          - conditions:
            - "{{trigger.event.data.value|int == 4}}"
            sequence:
              - if: >-
                  {{input_select.homestatus == "Normal"}}
                then:
                  - alias: "close the garage"
                    service: lock.lock
                    target:
                      entity_id: lock.garage_door
                  - alias: "set the home for away"
                    service: alarm_control_panel.alarm_arm_away
                    target:
                      entity_id: alarm_control_panel.simplisafe
                else:
                  - alias: "disable alarm"
                    service: alarm_control_panel.alarm_disarm
                    target:
                      entity_id: alarm_control_panel.simplisafe
                  - alias: "Wait for alarm to disarm"
                    wait_for_trigger:
                      - platform: state
                        entity_id: alarm_control_panel.simplisafe
                        to: "disarmed"
                    timeout:
                      seconds: 20
                  - if: '{{wait.trigger == None}}'
                    then:
                      - alias: "open the garage"
                        service: lock.unlock
                        target:
                          entity_id: lock.garage_door
                    else:
                      - alias: "notify alarm didn't disarm"
                        service: script.notify_parents
                        data:
                          title: Taliluna Alert
                          message: Could not disarm alarm
                          alert_level: Warn