sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: disk_free
        arg: "/"
      - type: memory_use_percent
      - type: memory_free
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot

automation:
  - id: 5f63716e-d11e-4aec-b8f7-5a9545496d27
    alias: Notify when server disk if full
    trigger:
      - platform: numeric_state
        entity_id: sensor.disk_use_percent
        above: 90
        for: "00:15:00"
      - platform: state
        entity_id: person.michael
        to: "home"
        for: "00:15:00"
    condition:
      - alias: "Server disk is full"
        condition: numeric_state
        entity_id: sensor.disk_use_percent
        above: 90
    action:
      - alias: "Notify"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Server disk is full