group:
  low_battery:
    name: Low Battery Sensors
    entities:
      - binary_sensor.node_27_low_battery_level
      - binary_sensor.multisensor_6_low_battery_level
      - binary_sensor.4_in_one_multisensor_low_battery_level
      - binary_sensor.z_wave_plus_thermostat_low_battery_level
      - binary_sensor.temperature_humidity_xs_sensor_low_battery_level
      - binary_sensor.touchscreen_electronic_deadbolt_low_battery_level
      - binary_sensor.touchscreen_electronic_deadbolt_low_battery_level_2
      - binary_sensor.touchscreen_electronic_deadbolt_low_battery_level_3
      - binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level
      - binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level_2
      - binary_sensor.zcombo_g_smoke_co_alarm_low_battery_level_3

automation:
  - alias: Battery Low Notification
    id: 70ff7438-1eb9-47b0-8121-9cd607cb4a99
    trigger:
      - platform: state
        entity_id: person.michael
        to: "home"
        for:
          minutes: 16
      - platform: state
        entity_id: group.low_battery
        from: "off"
        to: "on"
    condition:
      - alias: "There is a low battery"
        condition: state
        entity_id: group.low_battery
        state: "on"
      - alias: "Michael is home"
        condition: state
        entity_id: person.michael
        state: "home"
    action:
      - variables:
          entities: >-
            {% for sensor in expand("group.low_battery") if sensor.state == "off" -%}
              {{ state_attr(sensor.entity_id, "friendly_name") }}
              {%- if not loop.last %}, {% endif -%}
            {%- endfor %}
      - alias: "Send low battery notification"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Low battery detected on {{ entities }}
          alert_level: Warn
  - id: f8cdf062-1b0c-416f-8b56-a348d51fffcd
    alias: Yeti Battery Low
    trigger:
      - platform: numeric_state
        entity_id: sensor.yeti_state_of_charge_percent
        below: 81
        for: "00:00:00"
    condition: []
    action:
      - alias: "Notify adults"
        service: script.notify_parents
        data:
          title: Taliluna Alert
          message: Yeti Battery Low
          alert_level: Info